# Generated by Django 4.2.11 on 2026-09-11 10:58
"""The tenancies table: one rental agreement with one tenant. A new table only.

Depends on customers 0017, not on a newer customers migration. `makemigrations`
also offers an index rename on cronheartbeat and an alter on
payment.registration_fee in the customers app; both were outstanding before
this change and are left for the migration that owns them.
"""

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_seed_delivery_category'),
        ('customers', '0017_computerized_docs_consent'),
    ]

    operations = [
        # The foreign keys below lock business_customers and branches against
        # writes until this migration commits. Behind a long open write it would
        # queue, and writes queued behind it would wait too; giving up after 5s
        # fails the build instead, and the running deployment stays live.
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('sent', 'נשלח'), ('signed', 'נחתם'), ('active', 'פעיל'), ('ended', 'הסתיים'), ('cancelled', 'בוטל')], default='draft', max_length=20, verbose_name='סטטוס')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='סכום חודשי (לפני מע"מ)')),
                ('billing_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='יום חיוב בחודש')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='תחילת ההסכם')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='סיום ההסכם')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to='core.branch', verbose_name='סניף')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='customers.businesscustomer', verbose_name='שוכר')),
            ],
            options={
                'verbose_name': 'הסכם שכירות',
                'verbose_name_plural': 'הסכמי שכירות',
                'db_table': 'tenancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(check=models.Q(('billing_day__gte', 1), ('billing_day__lte', 28)), name='tenancy_billing_day_in_month'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(check=models.Q(('monthly_amount__gte', 0)), name='tenancy_monthly_amount_not_negative'),
        ),
    ]
