# Generated by Django 4.2.11 on 2026-09-11 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0001_initial'),
    ]

    operations = [
        # The foreign key to the user table locks it against writes until this
        # migration commits; fail the build after 5s rather than queue logins.
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(verbose_name='גרסה')),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('sent', 'נשלח'), ('viewed', 'נצפה'), ('signed', 'נחתם'), ('void', 'בוטל')], default='draft', max_length=20, verbose_name='סטטוס')),
                ('terms', models.JSONField(verbose_name='תנאי החוזה')),
                ('terms_sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256 של התנאים')),
                ('pdf', models.BinaryField(verbose_name='קובץ PDF')),
                ('pdf_sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256 של הקובץ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הפקה')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='תאריך ביטול')),
                ('void_reason', models.TextField(blank=True, verbose_name='סיבת ביטול')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='הופק על ידי')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rentals.tenancy', verbose_name='הסכם שכירות')),
            ],
            options={
                'verbose_name': 'חוזה שכירות',
                'verbose_name_plural': 'חוזי שכירות',
                'db_table': 'rental_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.UniqueConstraint(fields=('tenancy', 'version'), name='rental_contract_version_per_tenancy'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='rental_contract_version_from_one'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'sent', 'viewed'])), fields=('tenancy',), name='rental_contract_one_open_per_tenancy'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'signed')), fields=('tenancy',), name='rental_contract_one_signed_per_tenancy'),
        ),
    ]
