# Generated by Django 4.2.11 on 2026-09-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_signing_link_source'),
        ('rentals', '0002_rental_contracts'),
    ]

    operations = [
        # The foreign key to the signatures table locks it against inserts
        # (the widget's signature capture) until this migration commits; fail
        # the build after 5s rather than queue registrations behind it.
        # rental_contracts itself is new and empty in production, so every
        # column, the unique token index and the checks are instant there.
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='rentalcontract',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='נשלח לחתימה'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='sign_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='קוד קישור החתימה'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='sign_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='מועד יצירת הקישור'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_contracts', to='signatures.signature', verbose_name='חתימה'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='מועד החתימה'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='signed_pdf',
            field=models.BinaryField(blank=True, null=True, verbose_name='העותק החתום (PDF)'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='signed_pdf_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='SHA-256 של העותק החתום'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='נצפה לראשונה'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('signature__isnull', False), ('signed_at__isnull', False), ('signed_pdf__isnull', False), ('signed_pdf_sha256__isnull', False), ('status', 'signed')), models.Q(models.Q(('status', 'signed'), _negated=True), ('signature__isnull', True), ('signed_at__isnull', True), ('signed_pdf__isnull', True), ('signed_pdf_sha256__isnull', True)), _connector='OR'), name='rental_contract_signed_with_its_signature'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(check=models.Q(('sign_token__isnull', True), ('sign_token_created_at__isnull', False), _connector='OR'), name='rental_contract_link_has_its_time'),
        ),
    ]
