# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('inactive', 'לא פעיל'), ('payments_problem', 'בעיית תשלום')], default='active', max_length=20, verbose_name='סטטוס')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='מועד רישום')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_enrollments', to='customers.child', verbose_name='ילד')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.lesson', verbose_name='שיעור')),
            ],
            options={
                'verbose_name': 'רישום לשיעור',
                'verbose_name_plural': 'רישומים לשיעורים',
                'db_table': 'lesson_enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('lesson', 'child')},
            },
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField(blank=True, null=True, verbose_name='תאריך מופע')),
                ('status', models.CharField(choices=[('present', 'נוכח'), ('absent', 'נעדר'), ('not_marked', 'לא סומן')], default='not_marked', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='customers.child', verbose_name='ילד')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.lesson', verbose_name='שיעור')),
            ],
            options={
                'verbose_name': 'נוכחות',
                'verbose_name_plural': 'נוכחות',
                'db_table': 'lesson_attendance',
                'ordering': ['-created_at'],
                'unique_together': {('lesson', 'child', 'occurrence_date')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='מועד רישום')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='customers.child', verbose_name='ילד')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='חוג')),
            ],
            options={
                'verbose_name': 'רישום לחוג',
                'verbose_name_plural': 'רישומים לחוגים',
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'child')},
            },
        ),
        migrations.CreateModel(
            name='ChildAbsence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField(verbose_name='תאריך היעדרות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='customers.child', verbose_name='ילד')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_absences', to='courses.course', verbose_name='חוג')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_absences', to='courses.lesson', verbose_name='שיעור')),
            ],
            options={
                'verbose_name': 'היעדרות ילד',
                'verbose_name_plural': 'היעדרויות ילדים',
                'db_table': 'child_absences',
                'ordering': ['-occurrence_date'],
                'indexes': [models.Index(fields=['child', 'occurrence_date'], name='child_absen_child_i_b29042_idx'), models.Index(fields=['child', '-occurrence_date'], name='child_absen_child_i_705c0f_idx')],
                'unique_together': {('child', 'lesson', 'occurrence_date')},
            },
        ),
    ]
