# Generated by Django 4.2.11 on 2026-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lessonenrollment',
            index=models.Index(fields=['lesson', 'status'], name='lesson_enro_lesson__0cac24_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonenrollment',
            index=models.Index(fields=['status'], name='lesson_enro_status_acf4cd_idx'),
        ),
    ]
