# Generated by Django 4.2.11 on 2026-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_lessonenrollment_lesson_enro_lesson__0cac24_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='trial_evening_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תזכורת ערב נשלחה'),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='trial_followup_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תזכורת 72 שעות נשלחה'),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='trial_lesson_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך שיעור ניסיון'),
        ),
    ]
