# Generated by Django 4.2.11 on 2026-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_lessonenrollment_trial_10am_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollment',
            name='trial_evening_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תזכורת ערב נשלחה (לא בשימוש)'),
        ),
        migrations.AlterField(
            model_name='lessonenrollment',
            name='trial_followup_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='after-test נשלח'),
        ),
    ]
