# Generated by Django 4.2.11 on 2026-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_lessonenrollment_trial_evening_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='didnt_arrive_whatsapp_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set after 3 consecutive non-present marks; cleared when marked present again.', null=True, verbose_name='didnt_arrive WhatsApp נשלח'),
        ),
    ]
