# Generated by Django 4.2.11 on 2026-07-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lessonbundle'),
        ('enrollments', '0006_lessonenrollment_didnt_arrive_whatsapp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='מוגדר כאשר הרישום נוצר דרך הרשמה למסלול משולב — קובע חישוב מחיר לפי combined_price / מספר השיעורים במסלול.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.lessonbundle', verbose_name='מסלול משולב'),
        ),
    ]
