# Generated by Django 4.2.11 on 2026-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_lessonenrollment_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='ghost_visible_until',
            field=models.DateField(blank=True, help_text='Set only for walk-ins added from the attendance screen.', null=True, verbose_name='רפאים — מוצג עד'),
        ),
    ]
