# Generated by Django 4.2.11 on 2026-09-03 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_business_tags'),
        ('instructors', '0004_instructor_photo'),
        ('enrollments', '0008_lessonenrollment_ghost_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField(verbose_name='תאריך המופע')),
                ('kind', models.CharField(choices=[('lesson', 'תזכורת אחרי השיעור'), ('morning', 'סיכום בוקר על אתמול')], max_length=20, verbose_name='סוג')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='מועד שליחה')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_reminders', to='instructors.instructor', verbose_name='מדריך')),
                ('lesson', models.ForeignKey(blank=True, help_text='ריק בסיכום הבוקר, שמדבר על כל שיעורי היום הקודם.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_reminders', to='courses.lesson', verbose_name='שיעור')),
            ],
            options={
                'verbose_name': 'תזכורת הקראת נוכחות',
                'verbose_name_plural': 'תזכורות הקראת נוכחות',
                'db_table': 'register_reminders',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='registerreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('lesson', 'occurrence_date', 'kind'), name='uniq_register_reminder_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='registerreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', True)), fields=('instructor', 'occurrence_date', 'kind'), name='uniq_register_reminder_per_day'),
        ),
    ]
