# Generated by Django 4.2.11 on 2026-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_register_reminders'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registerreminder',
            name='uniq_register_reminder_per_lesson',
        ),
        migrations.AddIndex(
            model_name='registerreminder',
            index=models.Index(fields=['lesson', 'occurrence_date', 'kind', '-sent_at'], name='register_re_lesson__21b98c_idx'),
        ),
    ]
