# Generated by Django 4.2.11 on 2026-09-03 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_register_reminder_repeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerreminder',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='מועד שליחה'),
        ),
    ]
