# Generated by Django 4.2.11 on 2026-09-07 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0011_register_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='trial_outcome',
            field=models.CharField(blank=True, choices=[('attended', 'הגיע'), ('no_show', 'לא הגיע'), ('unmarked', 'לא סומן')], default='', help_text='נקבע לפי הנוכחות שסומנה בתאריך הניסיון, ברגע שהתאריך עבר.', max_length=20, verbose_name='תוצאת הניסיון'),
        ),
        migrations.CreateModel(
            name='TrialBlockedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='תאריך')),
                ('reason', models.CharField(blank=True, help_text='למשל: ראש השנה, חופשת סוכות.', max_length=120, verbose_name='סיבה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_blocked_dates', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
            ],
            options={
                'verbose_name': 'תאריך חסום לניסיון',
                'verbose_name_plural': 'תאריכים חסומים לניסיון',
                'db_table': 'trial_blocked_dates',
                'ordering': ['date'],
            },
        ),
    ]
