# Generated by Django 4.2.11 on 2026-09-08 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_recurring_override_store_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0020_course_business_tags'),
        ('enrollments', '0012_trial_outcome_and_blocked_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledUnitChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_unit_changes', to='customers.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_changes', to='enrollments.lessonenrollment')),
                ('recurring_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_unit_changes', to='customers.recurringpayment')),
                ('target_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lessonbundle')),
                ('target_lessons', models.ManyToManyField(related_name='+', to='courses.lesson')),
            ],
            options={
                'db_table': 'scheduled_unit_changes',
                'ordering': ['effective_date', 'created_at'],
            },
        ),
    ]
