# Generated by Django 4.2.11 on 2026-09-08 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0013_scheduled_unit_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialRegistrationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trials_open', models.BooleanField(default=True, verbose_name='הרשמה לשיעור ניסיון פתוחה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_registration_policies', to=settings.AUTH_USER_MODEL, verbose_name='עודכן על ידי')),
            ],
            options={
                'verbose_name': 'כלל הרשמה לשיעור ניסיון',
                'verbose_name_plural': 'כלל הרשמה לשיעור ניסיון',
                'db_table': 'trial_registration_policy',
            },
        ),
    ]
