# Generated by Django 4.2.11 on 2026-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_lesson_trial_registration_open'),
        ('enrollments', '0017_recover_lost_trial_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialblockeddate',
            name='lessons',
            field=models.ManyToManyField(blank=True, help_text='ריק = כל החוגים באותו יום.', related_name='trial_blocked_dates', to='courses.lesson', verbose_name='שיעורים'),
        ),
    ]
