# Generated by Django 4.2.11 on 2026-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_lesson_trial_registration_open'),
        # 0016, not 0017: the recovery migration is written but has not been
        # shipped, and a migration may not depend on one that is not in the
        # repository. When 0017 does ship it renumbers after this one.
        ('enrollments', '0016_trial_held_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialblockeddate',
            name='lessons',
            field=models.ManyToManyField(blank=True, help_text='ריק = כל החוגים באותו יום.', related_name='trial_blocked_dates', to='courses.lesson', verbose_name='שיעורים'),
        ),
    ]
