# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('customers', '0001_initial'),
        ('store', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product this payment is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='store.storeproduct', verbose_name='מוצר'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tranzila_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.tranzilatransaction', verbose_name='עסקת טרנזילה'),
        ),
        migrations.AddField(
            model_name='parent',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='customers.family', verbose_name='משפחה'),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entries', to='customers.child', verbose_name='ילד'),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_entries', to='courses.course', verbose_name='חוג'),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customers.invoice', verbose_name='חשבונית'),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='The specific lesson this invoice item is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_entries', to='courses.lesson', verbose_name='שיעור'),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product this invoice item is for (if not a lesson)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_entries', to='store.storeproduct', verbose_name='מוצר'),
        ),
        migrations.AddField(
            model_name='invoiceactivitylog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='customers.invoice', verbose_name='חשבונית'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.branch', verbose_name='סניף'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.family', verbose_name='משפחה'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.parent', verbose_name='הורה'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.payment', verbose_name='תשלום'),
        ),
        migrations.AddField(
            model_name='family',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.branch', verbose_name='סניף'),
        ),
        migrations.AddField(
            model_name='childstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='שונה על ידי'),
        ),
        migrations.AddField(
            model_name='childstatushistory',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='customers.child', verbose_name='ילד'),
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customers.family', verbose_name='משפחה'),
        ),
        migrations.AddField(
            model_name='branchdiscountmetrics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_metrics', to='core.branch', verbose_name='סניף'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['child', 'status'], name='recurring_p_child_i_50fac2_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['status', 'next_billing_date'], name='recurring_p_status_b28f83_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['tranzila_token'], name='recurring_p_tranzil_9bb457_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['child', 'status'], name='payments_child_i_74b1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['family', 'status'], name='payments_family__1ec02a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_status_db6b16_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='payments_payment_f51455_idx'),
        ),
        migrations.AddIndex(
            model_name='childstatushistory',
            index=models.Index(fields=['child', '-changed_at'], name='child_statu_child_i_cffc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='childstatushistory',
            index=models.Index(fields=['previous_status', 'new_status'], name='child_statu_previou_4da720_idx'),
        ),
        migrations.AddIndex(
            model_name='childstatushistory',
            index=models.Index(fields=['changed_at'], name='child_statu_changed_639060_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdiscountmetrics',
            index=models.Index(fields=['branch', 'month'], name='branch_disc_branch__35936e_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdiscountmetrics',
            index=models.Index(fields=['-month'], name='branch_disc_month_4d370c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchdiscountmetrics',
            unique_together={('branch', 'month')},
        ),
    ]
