# Generated by Django 4.2.11 on 2026-06-14 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='ת.ז')),
                ('company_number', models.CharField(blank=True, max_length=20, verbose_name='ח.פ')),
                ('business_type', models.CharField(blank=True, max_length=100, verbose_name='שיוך לעסק')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='קטגוריה')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'לקוח עסקי',
                'verbose_name_plural': 'לקוחות עסקיים',
                'db_table': 'business_customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
