# Generated by Django 4.2.11 on 2026-06-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_business_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscustomer',
            name='address',
            field=models.TextField(blank=True, verbose_name='כתובת'),
        ),
    ]
