# Generated by Django 4.2.11 on 2026-07-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lessonbundle'),
        ('customers', '0004_add_address_to_business_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='Set when this payment was billed as one lesson of a combined bundle registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.lessonbundle', verbose_name='מסלול משולב'),
        ),
    ]
