# Generated by Django 4.2.11 on 2026-09-07 14:42
#
# Hand-trimmed: the autodetector also picked up two changes that belong to
# nobody's request here — a CronHeartbeat index rename and a help_text edit on
# Payment.registration_fee, both already sitting in the models without a
# migration. They are left alone so this deployment carries only the override
# table; see docs/TASKS-OPEN.md.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_store_invoice_buyer_details'),
        ('customers', '0013_map_business_customer_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringChargeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_month', models.DateField(help_text='ה-1 בחודש שעבורו הסכום הזה מחליף את הסכום הרגיל.', verbose_name='חודש החיוב')),
                ('amount', models.DecimalField(decimal_places=2, help_text='הסכום שייגבה באותו חודש במקום הסכום הרגיל.', max_digits=10, verbose_name='סכום לחודש זה')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='הסכום שהיה נגבה ללא החריגה, כפי שהיה בזמן היצירה.', max_digits=10, null=True, verbose_name='הסכום הרגיל')),
                ('reason', models.TextField(help_text='הערה פנימית לצוות בלבד. אינה מוצגת להורה ואינה נכנסת למסמך.', verbose_name='סיבה')),
                ('source', models.CharField(choices=[('manual', 'שינוי ידני'), ('store', 'רכישה בחנות')], default='manual', max_length=20, verbose_name='מקור')),
                ('applied_at', models.DateTimeField(blank=True, help_text='נחתם כשהחיוב שהשתמש בחריגה נרשם כמוצלח. ריק = טרם נוצלה.', null=True, verbose_name='מועד הניצול')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'חריגת סכום לחודש',
                'verbose_name_plural': 'חריגות סכום לחודש',
                'db_table': 'recurring_charge_overrides',
                'ordering': ['billing_month'],
            },
        ),
        migrations.AddField(
            model_name='recurringchargeoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_amount_overrides', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי'),
        ),
        migrations.AddField(
            model_name='recurringchargeoverride',
            name='recurring_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_overrides', to='customers.recurringpayment', verbose_name='הוראת קבע'),
        ),
        migrations.AddField(
            model_name='recurringchargeoverride',
            name='store_invoice',
            field=models.ForeignKey(blank=True, help_text='החשבונית שהולידה את התוספת, כשהמקור הוא רכישה בחנות.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_overrides', to='store.storeinvoice', verbose_name='חשבונית חנות'),
        ),
        migrations.AddIndex(
            model_name='recurringchargeoverride',
            index=models.Index(fields=['recurring_payment', 'billing_month'], name='recurring_c_recurri_96405c_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringchargeoverride',
            constraint=models.UniqueConstraint(fields=('recurring_payment', 'billing_month'), name='uniq_recurring_override_per_month'),
        ),
    ]
