# Generated by Django 4.2.11
#
# Hand-trimmed, as 0014 was: the autodetector keeps picking up a CronHeartbeat
# index rename and a help_text edit on Payment.registration_fee that sit in the
# models without a migration and belong to nobody's request here.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_recurring_charge_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringchargeoverride',
            name='store_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='החלק מהסכום שמקורו במכירות בחנות. 0 כשאין.', max_digits=10, verbose_name='מתוך זה רכישות בחנות'),
        ),
    ]
