# Generated by Django 4.2.11 on 2026-09-10 14:21
#
# Renumbered 0017 -> 0018 when this branch was rebased: 0017 had been taken on
# main in the meantime. Two migrations sharing a number leaves the app with two
# leaf nodes, and Django then refuses to run `migrate` at all — which is the
# whole of the production build.
#
# Two unrelated operations that makemigrations wanted to fold in here were
# removed by hand: a RenameIndex on cronheartbeat and an AlterField on
# payment.registration_fee. Both are pre-existing model/migration drift that
# predates this change (see docs/05-BASELINE), and neither belongs to card
# replacement. Carrying them would make this migration apply somebody else's
# pending schema change without anyone deciding to.

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0017_computerized_docs_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('crm', 'הוקלד במערכת'), ('parent_link', 'הוזן על ידי ההורה בקישור')], default='crm', max_length=20, verbose_name='מקור')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 ספרות אחרונות')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='סוג כרטיס')),
                ('card_expire_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='חודש תפוגה')),
                ('card_expire_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='שנת תפוגה')),
                ('recurring_ids', models.JSONField(blank=True, default=list, verbose_name='הוראות קבע שעודכנו')),
                ('charged_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='סכום שנגבה')),
                ('results', models.JSONField(blank=True, default=list, help_text='שורה לכל חודש שנוסה: נגבה / נדחה / לא ודאי / דולג.', verbose_name='פירוט')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך')),
            ],
            options={
                'verbose_name': 'החלפת כרטיס',
                'verbose_name_plural': 'החלפות כרטיס',
                'db_table': 'card_replacements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='card_update_last_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תזכורת אחרונה'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='card_update_reminders_sent',
            field=models.PositiveIntegerField(default=0, help_text='כמה תזכורות לעדכון כרטיס נשלחו מאז הכישלון. מתאפס בהחלפת כרטיס.', verbose_name='תזכורות שנשלחו'),
        ),
        migrations.AddField(
            model_name='cardreplacement',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='ריק כשההורה הזין את הכרטיס בעצמו בקישור.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_replacements', to=settings.AUTH_USER_MODEL, verbose_name='מי ביצע'),
        ),
        migrations.AddField(
            model_name='cardreplacement',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_replacements', to='customers.family', verbose_name='משפחה'),
        ),
        migrations.AddIndex(
            model_name='cardreplacement',
            index=models.Index(fields=['family', '-created_at'], name='card_replac_family__3ab9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='cardreplacement',
            index=models.Index(fields=['-created_at'], name='card_replac_created_d23003_idx'),
        ),
    ]
