# Generated by Django 4.2.11 on 2026-09-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_child_status_canonical_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('active', 'פעיל'), ('trial_signed', 'נרשם לניסיון'), ('trial_completed', 'ביצע ניסיון'), ('pending', 'בתהליך רישום'), ('payment_problem', 'בעיה באשראי'), ('inactive', 'לא פעיל'), ('ghost', 'רפאים')], default='pending', max_length=20, verbose_name='סטטוס'),
        ),
    ]
