# Generated by Django 4.2.11 on 2026-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Which terminal each saved card and each charge belongs to.

    A branch push runs `migrate` on the production database before its code
    reaches main (vercel_build.py), so for a while the running code does not
    know these columns. Django adds them NOT NULL and drops the default; an
    insert from that code would then fail. The database keeps the '' default,
    so those inserts land as "the michal pair", which is what they are.
    """

    dependencies = [
        ('customers', '0022_business_customer_computerized_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='tranzila_terminal',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='מסוף הכרטיס השמור'),
        ),
        migrations.AddField(
            model_name='tranzilatransaction',
            name='tranzila_terminal',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='מסוף'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE recurring_payments ALTER COLUMN tranzila_terminal SET DEFAULT ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tranzila_transactions ALTER COLUMN tranzila_terminal SET DEFAULT ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
