# Generated by Django 4.2.11 on 2026-09-27 05:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_tranzila_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום העגלה')),
                ('page_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום בדיקת הכרטיס')),
                ('status', models.CharField(choices=[('page_open', 'עמוד תשלום פתוח'), ('verified', 'הכרטיס נבדק'), ('charging', 'בחיוב'), ('completed', 'הושלם'), ('declined', 'נדחה'), ('uncertain', 'לא ודאי'), ('review', 'לבדיקה'), ('replaced', 'הוחלף'), ('failed', 'נכשל')], db_index=True, default='page_open', max_length=20)),
                ('page_terminal', models.CharField(max_length=40, verbose_name='מסוף העמוד')),
                ('token_terminal', models.CharField(max_length=40, verbose_name='מסוף החיוב')),
                ('page_index', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='מספר עסקת הבדיקה')),
                ('page_confirmation_code', models.CharField(blank=True, max_length=40)),
                ('page_tranmode', models.CharField(blank=True, max_length=10)),
                ('card_token', models.CharField(blank=True, max_length=100)),
                ('card_expire_month', models.IntegerField(blank=True, null=True)),
                ('card_expire_year', models.IntegerField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_checkouts', to='customers.tranzilatransaction')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_checkouts', to='customers.family')),
                ('payments', models.ManyToManyField(related_name='course_checkouts', to='customers.payment')),
            ],
            options={
                'db_table': 'course_checkouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
