# Generated by Django 4.2.11 on 2026-10-02 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0024_course_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='widget_identification_blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='הזיהוי בטופס ההרשמה כובה במשרד'),
        ),
        migrations.AddField(
            model_name='family',
            name='widget_identification_blocked_reason',
            field=models.TextField(blank=True, null=True, verbose_name='סיבת כיבוי הזיהוי'),
        ),
        migrations.AddField(
            model_name='family',
            name='widget_identification_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='הסכמה לזיהוי בטופס ההרשמה'),
        ),
        migrations.CreateModel(
            name='WidgetRateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=30)),
                ('key_hash', models.CharField(max_length=64)),
                ('bucket_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'widget_rate_buckets',
                'indexes': [models.Index(fields=['bucket_start'], name='widget_rate_bucket__1aabef_idx')],
                'unique_together': {('scope', 'key_hash', 'bucket_start')},
            },
        ),
        migrations.CreateModel(
            name='WidgetIdentifyAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('id_hash', models.CharField(db_index=True, max_length=64)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('known', 'זוהה'), ('known_near', 'זוהה אחרי תיקון טלפון'), ('near', 'טלפון דומה — הוצע תיקון'), ('unknown', 'לא מוכר'), ('mismatch', 'ת.ז. מוכרת, טלפון אחר'), ('old', 'לקוח ישן'), ('no_consent', 'בלי הסכמה בתקנון'), ('hidden', 'כובה במשרד'), ('duplicate', 'שתי משפחות עם אותה ת.ז.'), ('locked', 'ת.ז. ננעלה אחרי ניסיונות שגויים'), ('device', 'יותר מדי הורים מאותו מכשיר'), ('network', 'יותר מדי הורים מאותה רשת'), ('cap', 'נעצר: יותר מדי זיהויים בשעה'), ('bot', 'נראה כמו רובוט')], db_index=True, max_length=20)),
                ('notice_sent', models.BooleanField(default=False)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identify_attempts', to='customers.family')),
            ],
            options={
                'db_table': 'widget_identify_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyIdentificationSwitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocked', models.BooleanField(verbose_name='הזיהוי כובה')),
                ('reason', models.TextField(verbose_name='סיבה')),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_identification_switches', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_switches', to='customers.family')),
            ],
            options={
                'db_table': 'family_identification_switches',
                'ordering': ['-changed_at'],
            },
        ),
    ]
