# Generated by Django 4.2.11 on 2026-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_widget_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='widget_contact_unproven_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='הטלפון בכרטיס הוחלף בלי הוכחה'),
        ),
        migrations.AlterField(
            model_name='widgetidentifyattempt',
            name='outcome',
            field=models.CharField(choices=[('known', 'זוהה'), ('known_near', 'זוהה אחרי תיקון טלפון'), ('near', 'טלפון דומה — הוצע תיקון'), ('unknown', 'לא מוכר'), ('mismatch', 'ת.ז. מוכרת, טלפון אחר'), ('old', 'לקוח ישן'), ('no_consent', 'בלי הסכמה בתקנון'), ('unproven_card', 'הטלפון בכרטיס הוחלף בלי הוכחה'), ('hidden', 'כובה במשרד'), ('duplicate', 'שתי משפחות עם אותה ת.ז.'), ('locked', 'ת.ז. ננעלה אחרי ניסיונות שגויים'), ('device', 'יותר מדי הורים מאותו מכשיר'), ('device_held', 'מכשיר שנחסם היום'), ('network', 'יותר מדי הורים מאותה רשת'), ('cap', 'נעצר: יותר מדי זיהויים בשעה'), ('bot', 'נראה כמו רובוט')], db_index=True, max_length=20),
        ),
    ]
