# Generated by Django 4.2.11 on 2026-10-02 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0026_widget_contact_unproven'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyIdentificationRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_hash', models.CharField(db_index=True, max_length=64)),
                ('released_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_releases', to='customers.family')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_identification_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_identification_releases',
                'ordering': ['-released_at'],
            },
        ),
    ]
