"""The record of each change to where a business customer is filed (7.10.2026).

One new table, business_customer_location_changes: who changed the location,
from what to what, how far the change went, and — when documents already issued
were moved with it — what each of them carried before. Additive: nothing that
exists is altered, and the code already deployed never reads or writes it.
"""

# Generated by Django 4.2.11 on 2026-10-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0027_identification_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCustomerLocationChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('first', 'שיוך ראשון'), ('future', 'מעכשיו והלאה'), ('all', 'גם מסמכים שכבר הופקו')], max_length=10, verbose_name='היקף השינוי')),
                ('previous_business_id', models.UUIDField(blank=True, null=True, verbose_name='העסק הקודם')),
                ('previous_category_id', models.UUIDField(blank=True, null=True, verbose_name='הקטגוריה הקודמת')),
                ('previous_branch_id', models.UUIDField(blank=True, null=True, verbose_name='הסניף הקודם')),
                ('previous_label', models.CharField(blank=True, max_length=320, verbose_name='המיקום הקודם')),
                ('new_business_id', models.UUIDField(blank=True, null=True, verbose_name='העסק החדש')),
                ('new_category_id', models.UUIDField(blank=True, null=True, verbose_name='הקטגוריה החדשה')),
                ('new_branch_id', models.UUIDField(blank=True, null=True, verbose_name='הסניף החדש')),
                ('new_label', models.CharField(blank=True, max_length=320, verbose_name='המיקום החדש')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='מסמכים ששויכו מחדש')),
                ('documents_changed', models.PositiveIntegerField(default=0, verbose_name='מספר המסמכים ששויכו מחדש')),
                ('changed_by_name', models.CharField(blank=True, max_length=150, verbose_name='שם המשנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='מתי')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_customer_location_changes', to=settings.AUTH_USER_MODEL, verbose_name='מי שינה')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_changes', to='customers.businesscustomer', verbose_name='לקוח עסקי')),
            ],
            options={
                'verbose_name': 'שינוי מיקום של לקוח עסקי',
                'verbose_name_plural': 'שינויי מיקום של לקוחות עסקיים',
                'db_table': 'business_customer_location_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='bc_location_change_customer')],
            },
        ),
    ]
