"""What the office decided about business customers that looked like one customer (7.10.2026).

One new table, business_customer_cleanups: a merge of several cards into one —
with every field of each card that went away — or a decision that the cards
are different customers. Additive: nothing that exists is altered, and the
code already deployed never reads or writes it.
"""

# Generated by Django 4.2.11 on 2026-10-07 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0028_business_customer_location_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCustomerCleanup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('merged', 'אוחדו לכרטיס אחד'), ('kept_apart', 'לקוחות שונים')], max_length=12, verbose_name='ההחלטה')),
                ('card_ids', models.JSONField(default=list, verbose_name='הכרטיסים')),
                ('merged_cards', models.JSONField(blank=True, default=list, verbose_name='הכרטיסים שאוחדו')),
                ('moved', models.JSONField(blank=True, default=dict, verbose_name='מה עבר לכרטיס שנשאר')),
                ('name_before', models.CharField(blank=True, max_length=210, verbose_name='השם לפני')),
                ('name_after', models.CharField(blank=True, max_length=210, verbose_name='השם אחרי')),
                ('decided_by_name', models.CharField(blank=True, max_length=150, verbose_name='שם המחליט')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='מתי')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_customer_cleanups', to=settings.AUTH_USER_MODEL, verbose_name='מי החליט')),
                ('survivor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanups', to='customers.businesscustomer', verbose_name='הכרטיס שנשאר')),
            ],
            options={
                'verbose_name': 'סידור לקוחות עסקיים',
                'verbose_name_plural': 'סידור לקוחות עסקיים',
                'db_table': 'business_customer_cleanups',
                'ordering': ['-created_at'],
            },
        ),
    ]
