"""A third decision the office can record: these cards are not business customers (7.10.2026).

Pupils of the lessons whom the previous software billed by hand came over as
business customers. Taking one off the list is recorded like a merge — the
whole card kept in the row. Choices only: no SQL runs.
"""

# Generated by Django 4.2.11 on 2026-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_business_customer_cleanups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscustomercleanup',
            name='action',
            field=models.CharField(choices=[('merged', 'אוחדו לכרטיס אחד'), ('kept_apart', 'לקוחות שונים'), ('removed', 'אינם לקוחות עסקיים')], max_length=12, verbose_name='ההחלטה'),
        ),
    ]
