# Generated by Django 4.2.11 on 2026-01-14 15:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Auto-generated invoice number', max_length=50, unique=True, verbose_name='מספר חשבונית')),
                ('customer_name', models.CharField(blank=True, help_text='For walk-in customers without child record', max_length=100, verbose_name='שם לקוח')),
                ('customer_phone', models.CharField(blank=True, help_text='For walk-in customers', max_length=20, verbose_name='טלפון לקוח')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='סכום כולל')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that has been refunded', max_digits=10, verbose_name='סכום שזוכה')),
                ('payment_method', models.CharField(choices=[('credit_card', 'אשראי'), ('cash', 'מזומן'), ('monthly_billing', 'הוראת קבע')], max_length=20, verbose_name='אמצעי תשלום')),
                ('payment_status', models.CharField(choices=[('pending', 'ממתין'), ('completed', 'הושלם'), ('failed', 'נכשל'), ('refunded', 'זוכה'), ('refund_failed', 'זיכוי נכשל')], default='pending', max_length=20, verbose_name='סטטוס תשלום')),
                ('tranzila_transaction_id', models.CharField(blank=True, help_text='Deprecated: Use tranzila_txn FK instead', max_length=100, verbose_name='מזהה עסקה טרנזילה')),
                ('tranzila_confirmation_code', models.CharField(blank=True, max_length=100, verbose_name='קוד אישור טרנזילה')),
                ('charged_with_token', models.BooleanField(default=False, help_text='True if charged using stored token (no iframe)', verbose_name='חויב עם טוקן')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הנפקה')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_invoices', to='core.branch', verbose_name='סניף')),
                ('child', models.ForeignKey(blank=True, help_text='Registered customer (null for walk-in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_invoices', to='customers.child', verbose_name='ילד')),
                ('tranzila_txn', models.ForeignKey(blank=True, help_text='Link to full Tranzila transaction record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_invoices', to='customers.tranzilatransaction', verbose_name='עסקת טרנזילה')),
            ],
            options={
                'verbose_name': 'חשבונית חנות',
                'verbose_name_plural': 'חשבוניות חנות',
                'db_table': 'store_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=100, verbose_name='שם מוצר')),
                ('category', models.CharField(default='כללי', help_text='Product category', max_length=50, verbose_name='קטגוריה')),
                ('size', models.CharField(blank=True, help_text='Comma-separated sizes (e.g., S,M,L,XL)', max_length=100, null=True, verbose_name='מידות')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price for profit calculation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='מחיר עלות')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Sale price to customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='מחיר מכירה')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)], verbose_name='כמות במלאי')),
                ('min_stock_alert', models.IntegerField(default=3, help_text='Alert when stock falls below this number', validators=[django.core.validators.MinValueValidator(0)], verbose_name='התראת מלאי מינימום')),
                ('image_url', models.URLField(blank=True, help_text='Product image URL', null=True, verbose_name='תמונה')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', verbose_name='הערות')),
                ('is_active', models.BooleanField(default=True, help_text='Active products appear in store', verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where product is located (null = delivery/online)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='core.branch', verbose_name='סניף')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'db_table': 'store_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='כמות')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='מחיר יחידה')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='סכום כולל')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='מידה')),
                ('payment_method', models.CharField(choices=[('credit_card', 'אשראי'), ('cash', 'מזומן'), ('monthly_billing', 'הוראת קבע')], max_length=20, verbose_name='אמצעי תשלום')),
                ('notes', models.TextField(blank=True, default='', verbose_name='הערות')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='תאריך מכירה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sales', to='core.branch', verbose_name='סניף')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_purchases', to='customers.child', verbose_name='ילד')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='store.storeinvoice', verbose_name='חשבונית')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.storeproduct', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'מכירה',
                'verbose_name_plural': 'מכירות',
                'db_table': 'store_sales',
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['product'], name='store_sales_product_a695de_idx'), models.Index(fields=['child'], name='store_sales_child_i_cedd45_idx'), models.Index(fields=['-sale_date'], name='store_sales_sale_da_f095ed_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['name'], name='store_produ_name_e5394d_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['branch'], name='store_produ_branch__c768e5_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['stock_quantity'], name='store_produ_stock_q_d3296b_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['-created_at'], name='store_produ_created_28a06c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinvoice',
            index=models.Index(fields=['invoice_number'], name='store_invoi_invoice_ca7880_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinvoice',
            index=models.Index(fields=['child'], name='store_invoi_child_i_d31602_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinvoice',
            index=models.Index(fields=['payment_status'], name='store_invoi_payment_94e6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinvoice',
            index=models.Index(fields=['-issue_date'], name='store_invoi_issue_d_e4dba3_idx'),
        ),
    ]
