# Generated by Django 4.2.11 on 2026-05-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeproductsize_unique_product_size_branch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeproductsize',
            new_name='store_produ_product_fc0df9_idx',
            old_name='store_produ_product_psize_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproductsize',
            new_name='store_produ_product_c3cb71_idx',
            old_name='store_produ_product_size_idx',
        ),
    ]
