# Generated by Django 4.2.11 on 2026-05-29 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_rename_store_produ_product_psize_idx_store_produ_product_fc0df9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_delta', models.IntegerField(help_text='חיובי = הוספה, שלילי = הפחתה', verbose_name='שינוי כמות')),
                ('reason', models.CharField(choices=[('receipt', 'קבלת סחורה'), ('theft', 'גניבה'), ('damage', 'בלאי / נזק'), ('recount', 'ספירה / תיקון'), ('other', 'אחר')], max_length=20, verbose_name='סיבה')),
                ('note', models.TextField(blank=True, default='', verbose_name='הערה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='בוצע על ידי')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='store.storeproduct', verbose_name='מוצר')),
                ('size_stock', models.ForeignKey(blank=True, help_text='השורה המדויקת שעודכנה (null = מלאי כולל)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to='store.storeproductsize', verbose_name='שורת מידה')),
            ],
            options={
                'verbose_name': 'התאמת מלאי',
                'verbose_name_plural': 'התאמות מלאי',
                'db_table': 'store_inventory_adjustments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='store_inven_product_b5851f_idx'), models.Index(fields=['-created_at'], name='store_inven_created_ca2fd1_idx'), models.Index(fields=['reason'], name='store_inven_reason_8db540_idx')],
            },
        ),
    ]
