# Generated by Django 4.2.11 on 2026-06-07 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_inventory_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far against this invoice (for partial payments / collections tracking)', max_digits=10, verbose_name='סכום ששולם'),
        ),
        migrations.AlterField(
            model_name='storeinvoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('completed', 'הושלם'), ('partially_paid', 'שולם חלקית'), ('failed', 'נכשל'), ('refunded', 'זוכה'), ('refund_failed', 'זיכוי נכשל')], default='pending', max_length=20, verbose_name='סטטוס תשלום'),
        ),
    ]
