# Generated by Django 4.2.11 on 2026-09-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_storeproduct_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinvoice',
            name='customer_notes',
            field=models.TextField(blank=True, default='', help_text='Free text the customer left at website checkout', verbose_name='הערות הלקוח'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='shipping_address',
            field=models.CharField(blank=True, default='', help_text='As typed at website checkout; the pickup branch label for pickups', max_length=255, verbose_name='כתובת למשלוח'),
        ),
        migrations.AlterField(
            model_name='storeinvoice',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='For walk-in / website customers', max_length=254, verbose_name='אימייל לקוח'),
        ),
    ]
