# Generated by Django 4.2.11 on 2026-09-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    The terminal each store invoice was charged on.

    A branch push runs `migrate` on the production database before its code
    reaches main (vercel_build.py), so for a while the running code does not
    know this column. Django adds it NOT NULL and then drops the default; an
    insert from that code would then fail and stop every sale. The database
    keeps the '' default, so old inserts land as "unknown terminal".
    """

    dependencies = [
        ('store', '0014_store_invoice_buyer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinvoice',
            name='tranzila_terminal',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='מסוף טרנזילה'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE store_invoices ALTER COLUMN tranzila_terminal SET DEFAULT ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
