# Generated by Django 4.2.11 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    What a store invoice keeps for following a hosted-page payment up
    (apps/store/payment_followup.py): when the website acknowledged "paid",
    when the CRM last followed the payment up by itself, when Tranzila first
    reported a payment, when the first and the last payment page were handed out,
    when the report was last searched for a payment of those pages, when a
    request to pay again was last told to wait, every further transaction
    number Tranzila reported, and what a person decided about a payment in
    review.

    Rolling this back (migrate store 0015) drops other_transactions and
    payment_review_log, and with them numbers nothing else keeps. A retreat
    from this change is a revert of the code only: the columns stay, NULL
    and unread.

    A branch push runs `migrate` on the production database before its code
    reaches main (vercel_build.py), so for a while the running code does not
    know these columns. Unlike 0015 there is nothing to keep here: every
    column is NULL-able, Django adds them without a default and without NOT
    NULL, and an insert from the old code lands as NULL — "nothing reported,
    nothing acknowledged, never followed up", which is exactly what an
    invoice the old code wrote is. No row is rewritten.
    """

    dependencies = [
        ('store', '0015_store_invoice_tranzila_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinvoice',
            name='website_paid_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='האתר אישר שקיבל את התשלום'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_followup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='בדיקת תשלום אחרונה'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='מועד דיווח התשלום'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_page_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='עמוד תשלום נפתח'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_page_first_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='עמוד תשלום ראשון נפתח'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_search_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='חיפוש תשלום בדוח — אחרון'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_retry_refused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='בקשת תשלום חוזרת נדחתה — ממתין לדוח'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='other_transactions',
            field=models.JSONField(blank=True, null=True, verbose_name='מספרי עסקה נוספים שדווחו'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='payment_review_log',
            field=models.JSONField(blank=True, null=True, verbose_name='החלטות על תשלום בבדיקה'),
        ),
    ]
