# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=100, verbose_name='שם משפחה')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='התמחות')),
                ('salary_model_type', models.CharField(choices=[('fixed_per_lesson', 'שכר קבוע לשיעור'), ('tiered_by_students', 'מדורג לפי תלמידים')], default='fixed_per_lesson', max_length=50, verbose_name='סוג מודל שכר')),
                ('fixed_salary_per_lesson', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='שכר קבוע לשיעור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('primary_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_instructors', to='core.branch', verbose_name='סניף ראשי')),
            ],
            options={
                'verbose_name': 'מדריך',
                'verbose_name_plural': 'מדריכים',
                'db_table': 'instructors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorSalaryTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_students', models.PositiveIntegerField(verbose_name='מינימום תלמידים')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='מקסימום תלמידים')),
                ('salary_per_lesson', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='שכר לשיעור')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_tiers', to='instructors.instructor', verbose_name='מדריך')),
            ],
            options={
                'verbose_name': 'מדרגת שכר',
                'verbose_name_plural': 'מדרגות שכר',
                'db_table': 'instructor_salary_tiers',
                'ordering': ['instructor', 'min_students'],
            },
        ),
        migrations.CreateModel(
            name='InstructorBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_type', models.CharField(choices=[('one_time', 'חד פעמי')], default='one_time', max_length=20, verbose_name='סוג בונוס')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום')),
                ('bonus_date', models.DateField(verbose_name='תאריך בונוס')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='תחילת תקופה')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='סוף תקופה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='instructors.instructor', verbose_name='מדריך')),
            ],
            options={
                'verbose_name': 'בונוס',
                'verbose_name_plural': 'בונוסים',
                'db_table': 'instructor_bonuses',
                'ordering': ['-bonus_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='core.branch', verbose_name='סניף')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='instructors.instructor', verbose_name='מדריך')),
            ],
            options={
                'verbose_name': 'שיוך מדריך לסניף',
                'verbose_name_plural': 'שיוכי מדריכים לסניפים',
                'db_table': 'instructor_branches',
                'unique_together': {('instructor', 'branch')},
            },
        ),
    ]
