# Generated by Django 4.2.11 on 2026-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_instructor_optional_last_name_and_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='קישור לתמונה'),
        ),
    ]
