# Generated by Django 4.2.11 on 2026-09-03 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_instructor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorPairPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=500, verbose_name='קישור לתמונה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('first_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_photos_as_first', to='instructors.instructor', verbose_name='מדריך א')),
                ('second_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_photos_as_second', to='instructors.instructor', verbose_name='מדריך ב')),
            ],
            options={
                'verbose_name': 'תמונה משותפת למדריכים',
                'verbose_name_plural': 'תמונות משותפות למדריכים',
                'db_table': 'instructor_pair_photos',
            },
        ),
        migrations.AddConstraint(
            model_name='instructorpairphoto',
            constraint=models.UniqueConstraint(fields=('first_instructor', 'second_instructor'), name='uniq_instructor_pair_photo'),
        ),
    ]
