# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='שם הסניף')),
                ('address', models.TextField(blank=True, verbose_name='כתובת')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='שם מנהל')),
                ('branch_codes', models.JSONField(blank=True, default=list, verbose_name='קודי סניף')),
                ('cleaning_managers', models.JSONField(blank=True, default=list, verbose_name='אחראי ניקיון')),
                ('cleaning_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='עלות ניקיון')),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='עלות חודשית')),
                ('wifi_name', models.CharField(blank=True, max_length=100, verbose_name='שם WiFi')),
                ('wifi_code', models.CharField(blank=True, max_length=100, verbose_name='סיסמת WiFi')),
                ('bluetooth_codes', models.JSONField(blank=True, default=list, verbose_name='קודי Bluetooth')),
                ('custom_details', models.JSONField(blank=True, default=list, verbose_name='פרטים מותאמים אישית')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'סניף',
                'verbose_name_plural': 'סניפים',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='שם קובץ')),
                ('file_type', models.CharField(choices=[('video', 'וידאו'), ('document', 'מסמך')], max_length=20, verbose_name='סוג קובץ')),
                ('file', models.FileField(upload_to='branch_files/', verbose_name='קובץ')),
                ('file_size', models.IntegerField(verbose_name='גודל קובץ')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='סוג MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'קובץ סניף',
                'verbose_name_plural': 'קבצי סניפים',
                'db_table': 'branch_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchMonthlySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7, verbose_name='חודש')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='סה״כ תלמידים')),
                ('base_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue before discounts', max_digits=10, verbose_name='הכנסות תיאורטיות')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סה״כ הנחות')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Actual collected revenue (from completed payments)', max_digits=10, verbose_name='סה״כ הכנסות')),
                ('instructor_salaries', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='שכר מדריכים')),
                ('instructor_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='בונוסים למדריכים')),
                ('operational_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='הוצאות תפעוליות')),
                ('instructor_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סה״כ הוצאות')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='רווח')),
                ('active_courses_count', models.PositiveIntegerField(default=0, verbose_name='חוגים פעילים')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='חודש סופי')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='חושב בתאריך')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'צילום חודשי - סניף',
                'verbose_name_plural': 'צילומים חודשיים - סניפים',
                'db_table': 'branch_monthly_snapshots',
                'ordering': ['-month', 'branch'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='שם העיר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'עיר',
                'verbose_name_plural': 'ערים',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorMonthlySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7, verbose_name='חודש')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='סה״כ שיעורים')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='סה״כ תלמידים')),
                ('base_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue before discounts (lesson price × students)', max_digits=10, verbose_name='הכנסות תיאורטיות')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סה״כ הנחות')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Actual collected revenue (from completed payments)', max_digits=10, verbose_name='סה״כ הכנסות')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סה״כ שכר')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סה״כ בונוסים')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='רווח')),
                ('cancelled_count', models.PositiveIntegerField(default=0, verbose_name='שיעורים שבוטלו')),
                ('avg_attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='אחוז נוכחות ממוצע')),
                ('lesson_count', models.PositiveIntegerField(default=0, verbose_name='מספר שיעורים שהתרחשו')),
                ('payment_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='תשלום לשיעור (צילום)')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='חודש סופי')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='חושב בתאריך')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'צילום חודשי - מדריך',
                'verbose_name_plural': 'צילומים חודשיים - מדריכים',
                'db_table': 'instructor_monthly_snapshots',
                'ordering': ['-month', 'instructor'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker')], default='worker', max_length=20, verbose_name='תפקיד')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'פרופיל משתמש',
                'verbose_name_plural': 'פרופילי משתמשים',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='שם החדר')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='קיבולת')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='ייעוד')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.branch', verbose_name='סניף')),
            ],
            options={
                'verbose_name': 'חדר',
                'verbose_name_plural': 'חדרים',
                'db_table': 'rooms',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonMonthlySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7, verbose_name='חודש')),
                ('enrolled_students', models.PositiveIntegerField(default=0, verbose_name='תלמידים רשומים')),
                ('base_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue before discounts', max_digits=10, verbose_name='הכנסות תיאורטיות')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סה״כ הנחות')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Actual collected revenue (from completed payments)', max_digits=10, verbose_name='הכנסות')),
                ('instructor_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='שכר מדריך')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='רווח')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='חודש סופי')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='חושב בתאריך')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_snapshots', to='core.branch', verbose_name='סניף')),
            ],
            options={
                'verbose_name': 'צילום חודשי - שיעור',
                'verbose_name_plural': 'צילומים חודשיים - שיעורים',
                'db_table': 'lesson_monthly_snapshots',
                'ordering': ['-month', 'lesson'],
            },
        ),
    ]
