# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmonthlysnapshot',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_snapshots', to='courses.course', verbose_name='חוג'),
        ),
        migrations.AddField(
            model_name='lessonmonthlysnapshot',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_snapshots', to='instructors.instructor', verbose_name='מדריך'),
        ),
        migrations.AddField(
            model_name='lessonmonthlysnapshot',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='courses.lesson', verbose_name='שיעור'),
        ),
        migrations.AddField(
            model_name='instructormonthlysnapshot',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='instructors.instructor', verbose_name='מדריך'),
        ),
        migrations.AddField(
            model_name='branchmonthlysnapshot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='core.branch', verbose_name='סניף'),
        ),
        migrations.AddField(
            model_name='branchfile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.branch', verbose_name='סניף'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='core.city', verbose_name='עיר'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonmonthlysnapshot',
            unique_together={('lesson', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='instructormonthlysnapshot',
            unique_together={('instructor', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='branchmonthlysnapshot',
            unique_together={('branch', 'month')},
        ),
    ]
