# Generated by Django 4.2.11 on 2026-06-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_partner_role_and_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='סניף חיצוני'),
        ),
    ]
