# Generated by Django 4.2.11 on 2026-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='לינק לסניף'),
        ),
    ]
