# Generated by Django 4.2.11 on 2026-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_branch_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='external_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='לינק לסניף'),
        ),
    ]
