# Generated by Django 4.2.11 on 2026-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='מספר כניסות'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tour_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user finishes or dismisses the tour; stops it opening again.', null=True, verbose_name='סיים הדרכה'),
        ),
    ]
