# Generated by Django 4.2.11 on 2026-08-31 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_reset_tour_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users_created', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('linked', models.ForeignKey(help_text='המשתמש שאותו מותר לצפות', on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to=settings.AUTH_USER_MODEL, verbose_name='משתמש מקושר')),
                ('owner', models.ForeignKey(help_text='המשתמש שמקבל את ההרשאה לצפות', on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'משתמש מקושר',
                'verbose_name_plural': 'משתמשים מקושרים',
                'db_table': 'linked_user_access',
            },
        ),
        migrations.AddConstraint(
            model_name='linkeduseraccess',
            constraint=models.UniqueConstraint(fields=('owner', 'linked'), name='uniq_linked_user_pair'),
        ),
        migrations.AddConstraint(
            model_name='linkeduseraccess',
            constraint=models.CheckConstraint(check=models.Q(('owner', models.F('linked')), _negated=True), name='linked_user_not_self'),
        ),
    ]
