# Generated by Django 4.2.11 on 2026-08-31 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reset_tour_state_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeduseraccess',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='השאירו ריק כדי לצפות בכל הסניפים של המשתמש המקושר', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_user_access', to='core.branch', verbose_name='סניף'),
        ),
    ]
