# Generated by Django 4.2.11 on 2026-08-31 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_linked_user_access_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='שם ההגדרה')),
                ('value', models.TextField(verbose_name='ערך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_credentials_set', to=settings.AUTH_USER_MODEL, verbose_name='עודכן על ידי')),
            ],
            options={
                'verbose_name': 'הגדרת חיבור',
                'verbose_name_plural': 'הגדרות חיבור',
                'db_table': 'integration_credentials',
            },
        ),
    ]
