# Generated by Django 4.2.11 on 2026-09-02 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_integration_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם העסק')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='סדר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'עסק',
                'verbose_name_plural': 'עסקים',
                'db_table': 'businesses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='שם הקטגוריה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='סדר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.business', verbose_name='עסק')),
            ],
            options={
                'verbose_name': 'קטגוריית עסק',
                'verbose_name_plural': 'קטגוריות עסק',
                'db_table': 'business_categories',
                'ordering': ['business', 'sort_order', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
    ]
