# Generated by Django 4.2.11 on 2026-09-25 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_system_audit_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='טביעת המפתח')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='דפדפן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='התחבר')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='שימוש אחרון')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'התחברות ממכשיר',
                'verbose_name_plural': 'התחברויות ממכשירים',
                'db_table': 'login_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
