# Generated by Django 4.2.11 on 2026-09-27 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_login_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=60, verbose_name='סוג')),
                ('dedup_key', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='מה קרה')),
                ('where', models.CharField(max_length=300, verbose_name='איפה')),
                ('what', models.CharField(max_length=500, verbose_name='פירוט')),
                ('why', models.CharField(blank=True, max_length=500, verbose_name='למה')),
                ('customer', models.CharField(blank=True, max_length=500, verbose_name='הלקוח')),
                ('action', models.CharField(blank=True, max_length=300, verbose_name='מה לעשות')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='קישור')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'ממתינה לשליחה'), ('sent', 'נשלחה'), ('failed', 'השליחה נכשלה'), ('not_configured', 'ווטסאפ למשרד לא הוגדר')], db_index=True, default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'office_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
