# Generated by Django 4.2.11 on 2026-10-01 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_office_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayoutTerminalMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal', models.CharField(max_length=40, verbose_name='מסוף')),
                ('month', models.DateField(verbose_name='חודש הגבייה')),
                ('charges_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='חיובים שאושרו')),
                ('charges_count', models.PositiveIntegerField(default=0, verbose_name='מספר חיובים')),
                ('refunds_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='זיכויים')),
                ('refunds_count', models.PositiveIntegerField(default=0, verbose_name='מספר זיכויים')),
                ('installments_count', models.PositiveIntegerField(default=0, verbose_name='עסקאות בתשלומים')),
                ('installments_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='סכום העסקאות בתשלומים')),
                ('installments_first_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='סכום התשלומים הראשונים')),
                ('complete', models.BooleanField(default=False, verbose_name='הדוח נקרא במלואו')),
                ('error', models.TextField(blank=True, default='', verbose_name='שגיאה בקריאת הדוח')),
                ('fetched_at', models.DateTimeField(verbose_name='נקרא מטרנזילה ב')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
            ],
            options={
                'verbose_name': 'דוח חודשי של מסוף',
                'verbose_name_plural': 'דוחות חודשיים של מסופים',
                'db_table': 'card_payout_terminal_months',
                'ordering': ['-month', 'terminal'],
            },
        ),
        migrations.AddConstraint(
            model_name='cardpayoutterminalmonth',
            constraint=models.UniqueConstraint(fields=('terminal', 'month'), name='card_payout_one_per_terminal_month'),
        ),
    ]
