# Generated by Django 4.2.11 on 2026-10-02 10:08

from django.db import migrations, models

# How to get in from the street, as the owner dictated it on 2.10.2026 — for
# the calendar event of a trial lesson. Matched by what the branch's own card
# says (its address, else its name); a branch that already has directions keeps
# them, and a branch not listed here gets none: its address stands alone.
DIRECTIONS = (
    ('address', 'מינץ 24', 'נכנסים לחניה של סופר טל, והסטודיו משמאל.'),
    ('name', 'דמרי', 'קניון דימרי סנטר, קומה מינוס 1.'),
    ('address', 'קרל וגרטי קורי', 'מתחם הקבלנים. נכנסים לחניה הגדולה; הסטודיו בצד ימין של הפארק, מול הצופים.'),
    ('name', 'ניצנים', 'בית ספר ניצנים. נכנסים לחניה שמתחת לאולם הספורט, ולבית הספר בשביל הימני, שמוביל לסטודיו.'),
)


def fill_directions(apps, schema_editor):
    Branch = apps.get_model('core', 'Branch')
    for field, needle, words in DIRECTIONS:
        for branch in Branch.objects.filter(**{f'{field}__contains': needle}):
            if (branch.arrival_directions or '').strip():
                continue
            branch.arrival_directions = words
            branch.save(update_fields=['arrival_directions'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_terms_identification_clause'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='arrival_directions',
            field=models.TextField(blank=True, null=True, verbose_name='איך מגיעים'),
        ),
        migrations.RunPython(fill_directions, migrations.RunPython.noop),
    ]
