# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='שם החוג')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
                ('capacity', models.PositiveIntegerField(verbose_name='קיבולת')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='גיל מינימום')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='גיל מקסימום')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.branch', verbose_name='סניף')),
            ],
            options={
                'verbose_name': 'חוג',
                'verbose_name_plural': 'חוגים',
                'db_table': 'courses',
                'ordering': ['course_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='שם התחום')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'תחום',
                'verbose_name_plural': 'תחומים',
                'db_table': 'course_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'ראשון'), (1, 'שני'), (2, 'שלישי'), (3, 'רביעי'), (4, 'חמישי'), (5, 'שישי'), (6, 'שבת')], verbose_name='יום בשבוע')),
                ('start_time', models.TimeField(verbose_name='שעת התחלה')),
                ('end_time', models.TimeField(verbose_name='שעת סיום')),
                ('lesson_date', models.DateField(blank=True, null=True, verbose_name='תאריך שיעור')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='מחיר שיעור')),
                ('lesson_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='מחיר מותאם')),
                ('instructor_salary_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='שכר מדריך מותאם')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='חוזר שבועית')),
                ('status', models.CharField(choices=[('scheduled', 'מתוכנן'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='scheduled', max_length=20, verbose_name='סטטוס')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='סיבת ביטול')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='בוטל בתאריך')),
                ('room_text', models.CharField(blank=True, max_length=100, verbose_name='חדר (טקסט)')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.branch', verbose_name='סניף')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='חוג')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='instructors.instructor', verbose_name='מדריך')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.room', verbose_name='חדר')),
            ],
            options={
                'verbose_name': 'שיעור',
                'verbose_name_plural': 'שיעורים',
                'db_table': 'lessons',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursetype', verbose_name='תחום'),
        ),
    ]
