# Generated by Django 4.2.11 on 2026-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_additional_course_prices'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['branch', 'status'], name='lessons_branch__097a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['branch', 'course'], name='lessons_branch__07b2f9_idx'),
        ),
    ]
