# Generated by Django 4.2.11 on 2026-05-29 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_move_branch_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='מנהלים שיכולים לראות ולנהל חוג זה. ריק = אף מנהל (מלבד מנהל-על).', related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='מנהלים מורשים'),
        ),
    ]
