# Generated by Django 4.2.11 on 2026-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_salary_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='תשלום חודשי למדריך עבור הקבוצה (לא לשיעור בודד).', max_digits=10, null=True, verbose_name='שכר מדריך חודשי לקבוצה'),
        ),
    ]
