# Generated by Django 4.2.11 on 2026-07-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_is_adult_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_link',
            field=models.CharField(blank=True, help_text='לינק הרשמה חיצוני ספציפי לחוג זה (רלוונטי רק לסניפים חיצוניים). ריק = שימוש בלינק של הסניף.', max_length=500, verbose_name='לינק חיצוני לחוג'),
        ),
    ]
