# Generated by Django 4.2.11 on 2026-07-27 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remap_age_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='שם המסלול')),
                ('combined_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר משולב')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bundles', to='courses.course', verbose_name='חוג')),
                ('lessons', models.ManyToManyField(related_name='bundles', to='courses.lesson', verbose_name='שיעורים במסלול')),
            ],
            options={
                'verbose_name': 'מסלול משולב',
                'verbose_name_plural': 'מסלולים משולבים',
                'db_table': 'lesson_bundles',
                'ordering': ['course', 'name'],
            },
        ),
    ]
