# Generated by Django 4.2.11 on 2026-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lessonbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='must_attend_all_lessons',
            field=models.BooleanField(default=False, verbose_name='מחוייב בכל השיעורים'),
        ),
    ]
