# Generated by Django 4.2.11 on 2026-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_business_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='trial_registration_open',
            field=models.BooleanField(blank=True, help_text='ריק — לפי הכלל הכללי; פתוח או סגור — החרגה לשיעור הזה בלבד', null=True, verbose_name='הרשמה לשיעור ניסיון'),
        ),
    ]
