# Generated by Django 4.2.11 on 2026-10-02 10:08

from django.db import migrations, models

# What to come with to a trial lesson, as the owner dictated it on 2.10.2026,
# and a short name for the title of a calendar event. Matched by the field's
# name; a field that already has a note keeps it, and a field not listed here
# gets none — the calendar event then says nothing about what to bring.
BRING = (
    ('קפוארה', 'מכנס ארוך. בשיעור מורידים נעליים.'),
    ('מחול', 'שיער אסוף, טייץ ונעליים.'),
    ('אווירית', 'טייץ ארוך. מורידים נעליים בתחילת השיעור.'),
)
SHORT_NAMES = {'היפהופ - מחול': 'ריקוד'}


def fill_notes(apps, schema_editor):
    CourseType = apps.get_model('courses', 'CourseType')
    for course_type in CourseType.objects.all():
        name = (course_type.name or '').strip()
        changed = []
        if not (course_type.trial_bring_note or '').strip():
            for needle, words in BRING:
                if needle in name:
                    course_type.trial_bring_note = words
                    changed.append('trial_bring_note')
                    break
        if not (course_type.short_name or '').strip() and name in SHORT_NAMES:
            course_type.short_name = SHORT_NAMES[name]
            changed.append('short_name')
        if changed:
            course_type.save(update_fields=changed)



class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_lesson_trial_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='short_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='שם קצר'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='trial_bring_note',
            field=models.TextField(blank=True, null=True, verbose_name='מה להביא לשיעור ניסיון'),
        ),
        migrations.RunPython(fill_notes, migrations.RunPython.noop),
    ]
