# Generated by Django 4.2.11 on 2026-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_trial_calendar_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='ריק = לפי קיבולת הקבוצה והחדר. מספר = השיעור הזה מתמלא בו, גם אם בקבוצה ובחדר יש מקום.', null=True, verbose_name='קיבולת לשיעור'),
        ),
    ]
