# Generated by Django 4.2.11 on 2026-09-11 15:47
"""Tenants' standing orders, their monthly charges and card links. New tables only.

Depends on customers 0017, not on a newer customers migration: `makemigrations`
also offers an index rename on cronheartbeat and an alter on
payment.registration_fee in the customers app; both were outstanding before
this change and are left for the migration that owns them. Depends on rentals
0002, so it sits beside the signing page's rentals 0003 rather than after it.
"""

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0007_credit_note_details'),
        ('customers', '0017_computerized_docs_consent'),
        ('core', '0020_terms_computerized_docs_clause'),
        ('rentals', '0002_rental_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The foreign keys below lock tenancies, business_customers, branches,
        # businesses, business_categories, formal_documents and the user table
        # against writes until this migration commits. Behind a long open write
        # it would queue, and writes queued behind it would wait too; giving up
        # after 5s fails the build instead, and the running deployment stays live.
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='TenantStandingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_before_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום חודשי (לפני מע"מ)')),
                ('billing_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='יום חיוב בחודש')),
                ('start_date', models.DateField(verbose_name='תחילת החיוב')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='סיום החיוב')),
                ('next_charge_date', models.DateField(blank=True, null=True, verbose_name='החיוב הבא')),
                ('status', models.CharField(choices=[('pending_card', 'ממתינה לכרטיס'), ('active', 'פעילה'), ('paused', 'מושהית'), ('failed', 'החיוב נכשל'), ('ended', 'הסתיימה')], default='pending_card', max_length=20, verbose_name='סטטוס')),
                ('tranzila_token', models.CharField(blank=True, max_length=200, verbose_name='טוקן כרטיס בטרנזילה')),
                ('card_expire_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='חודש תוקף')),
                ('card_expire_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='שנת תוקף')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 ספרות אחרונות')),
                ('source', models.CharField(choices=[('signing', 'חתימה על החוזה'), ('office', 'המשרד')], default='office', max_length=20, verbose_name='מקור')),
                ('last_error', models.TextField(blank=True, verbose_name='שגיאה אחרונה')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד הכישלון')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_standing_orders', to='core.branch', verbose_name='סניף')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.business', verbose_name='עסק')),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.businesscategory', verbose_name='קטגוריה בעסק')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_orders', to='rentals.tenancy', verbose_name='הסכם שכירות')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_standing_orders', to='customers.businesscustomer', verbose_name='שוכר')),
            ],
            options={
                'verbose_name': 'הוראת קבע של שוכר',
                'verbose_name_plural': 'הוראות קבע של שוכרים',
                'db_table': 'tenant_standing_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(verbose_name='חודש החיוב')),
                ('amount_before_vat', models.PositiveIntegerField(verbose_name='לפני מע"מ (אגורות)')),
                ('vat_amount', models.PositiveIntegerField(verbose_name='מע"מ (אגורות)')),
                ('total', models.PositiveIntegerField(verbose_name='סה"כ (אגורות)')),
                ('status', models.CharField(choices=[('reserved', 'שמור לחיוב'), ('charged', 'חויב'), ('failed', 'נדחה'), ('review', 'בבדיקה'), ('voided', 'בוטל')], default='reserved', max_length=20, verbose_name='סטטוס')),
                ('trigger', models.CharField(choices=[('cron', 'חיוב חודשי'), ('card', 'הזנת כרטיס'), ('retry', 'ניסיון חוזר מהמשרד')], max_length=20, verbose_name='מקור החיוב')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='ניסיונות')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 ספרות אחרונות')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='מזהה עסקה בטרנזילה')),
                ('confirmation_code', models.CharField(blank=True, max_length=50, verbose_name='מספר אישור')),
                ('response_code', models.CharField(blank=True, max_length=20, verbose_name='קוד תשובה')),
                ('error', models.TextField(blank=True, verbose_name='שגיאה')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='מועד השמירה')),
                ('charged_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד החיוב')),
                ('receipt_error', models.TextField(blank=True, verbose_name='שגיאת הפקת קבלה')),
                ('receipt_emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד שליחת הקבלה')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד ההכרעה')),
                ('resolution_note', models.TextField(blank=True, verbose_name='הערת הכרעה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.business', verbose_name='עסק')),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.businesscategory', verbose_name='קטגוריה בעסק')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_charge', to='documents.formaldocument', verbose_name='חשבונית מס/קבלה')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='הוכרע על ידי')),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='rental_billing.tenantstandingorder', verbose_name='הוראת קבע')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_charges', to='rentals.tenancy', verbose_name='הסכם שכירות')),
            ],
            options={
                'verbose_name': 'חיוב שוכר',
                'verbose_name_plural': 'חיובי שוכרים',
                'db_table': 'tenant_charges',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantCardLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='טוקן')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('processing', 'בעיבוד'), ('used', 'מומש'), ('cancelled', 'בוטל'), ('review', 'בבדיקה')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='ניסיונות')),
                ('charge_started_at', models.DateTimeField(blank=True, null=True, verbose_name='תחילת העיבוד')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד המימוש')),
                ('last_error', models.TextField(blank=True, verbose_name='שגיאה אחרונה')),
                ('review_reason', models.CharField(blank=True, max_length=200, verbose_name='סיבת הבדיקה')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_links', to='rental_billing.tenantstandingorder', verbose_name='הוראת קבע')),
            ],
            options={
                'verbose_name': 'קישור כרטיס לשוכר',
                'verbose_name_plural': 'קישורי כרטיס לשוכרים',
                'db_table': 'tenant_card_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantstandingorder',
            index=models.Index(fields=['status', 'next_charge_date'], name='tenant_so_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantstandingorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_card', 'active', 'paused', 'failed'])), fields=('tenancy',), name='tenant_standing_order_one_open_per_tenancy'),
        ),
        migrations.AddConstraint(
            model_name='tenantstandingorder',
            constraint=models.CheckConstraint(check=models.Q(('billing_day__gte', 1), ('billing_day__lte', 28)), name='tenant_standing_order_billing_day_in_month'),
        ),
        migrations.AddConstraint(
            model_name='tenantstandingorder',
            constraint=models.CheckConstraint(check=models.Q(('amount_before_vat__gt', 0)), name='tenant_standing_order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='tenantstandingorder',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tenant_standing_order_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='tenantcharge',
            index=models.Index(fields=['status', 'reserved_at'], name='tenant_charge_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantcharge',
            constraint=models.UniqueConstraint(fields=('tenancy', 'period'), name='tenant_charge_one_per_tenancy_month'),
        ),
        migrations.AddConstraint(
            model_name='tenantcharge',
            constraint=models.CheckConstraint(check=models.Q(('period__day', 1)), name='tenant_charge_period_first_of_month'),
        ),
        migrations.AddConstraint(
            model_name='tenantcharge',
            constraint=models.CheckConstraint(check=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('amount_before_vat'), '+', models.F('vat_amount')))), name='tenant_charge_total_is_net_plus_vat'),
        ),
        migrations.AddConstraint(
            model_name='tenantcardlink',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('standing_order',), name='tenant_card_link_one_live_per_order'),
        ),
    ]
