# Generated by Django 4.2.11 on 2026-06-14 05:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_business_customer'),
        ('core', '0005_userprofile_partner_role_and_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='מספר מסמך')),
                ('document_type', models.CharField(choices=[('tax_invoice', 'חשבונית מס'), ('receipt', 'קבלה'), ('combined', 'חשבונית מס/קבלה'), ('transaction_invoice', 'חשבונית עסקה'), ('credit_invoice', 'חשבונית מס זיכוי')], max_length=30, verbose_name='סוג מסמך')),
                ('client_type', models.CharField(choices=[('business', 'עסקי'), ('existing', 'קיים')], max_length=20, verbose_name='סוג לקוח')),
                ('document_date', models.DateField(verbose_name='תאריך מסמך')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='תאריך פירעון')),
                ('description', models.TextField(blank=True, verbose_name='פרטים')),
                ('currency', models.CharField(choices=[('ILS', 'שקל ₪'), ('USD', 'דולר $'), ('EUR', 'אירו €')], default='ILS', max_length=3, verbose_name='מטבע')),
                ('prices_include_vat', models.BooleanField(default=False, verbose_name='מחירים כוללים מע"מ')),
                ('payment_terms', models.CharField(blank=True, max_length=30, verbose_name='תנאי תשלום')),
                ('vat_exempt', models.BooleanField(default=False, verbose_name='פטור ממע"מ')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='אחוז מע"מ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סכום לפני הנחה')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='הנחה בשקלים')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='הנחה באחוזים')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סכום מע"מ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ')),
                ('customer_notes', models.TextField(blank=True, verbose_name='הערות ללקוח')),
                ('internal_notes', models.TextField(blank=True, verbose_name='הערה פנימית')),
                ('linked_document_number', models.CharField(blank=True, max_length=30, verbose_name='מספר חשבונית מקושרת')),
                ('credit_reason', models.TextField(blank=True, verbose_name='סיבת זיכוי')),
                ('tranzila_doc_id', models.CharField(blank=True, max_length=100, verbose_name='מזהה מסמך טרנזילה')),
                ('tranzila_retrieval_key', models.CharField(blank=True, max_length=100, verbose_name='מפתח אחזור טרנזילה')),
                ('pdf_url', models.URLField(blank=True, verbose_name='קישור PDF')),
                ('tranzila_issued', models.BooleanField(default=False, verbose_name='הופק בטרנזילה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='סניף')),
                ('business_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formal_documents', to='customers.businesscustomer', verbose_name='לקוח עסקי')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formal_documents', to='customers.child', verbose_name='ילד')),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='documents.formaldocument', verbose_name='מסמך מקושר')),
            ],
            options={
                'verbose_name': 'מסמך פיננסי',
                'verbose_name_plural': 'מסמכים פיננסיים',
                'db_table': 'formal_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'מזומן'), ('check', "צ'ק"), ('credit_card', 'אשראי'), ('bank_transfer', 'העברה בנקאית')], max_length=20, verbose_name='אמצעי תשלום')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סכום')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='אסמכתא / מספר')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name="תאריך צ'ק")),
                ('check_bank', models.CharField(blank=True, max_length=100, verbose_name='בנק')),
                ('check_branch', models.CharField(blank=True, max_length=50, verbose_name='סניף')),
                ('check_account', models.CharField(blank=True, max_length=50, verbose_name='מספר חשבון')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='4 ספרות אחרונות')),
                ('card_expiry', models.CharField(blank=True, max_length=7, verbose_name='תוקף')),
                ('card_installments', models.PositiveSmallIntegerField(default=1, verbose_name='מספר תשלומים')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='documents.formaldocument')),
            ],
            options={
                'verbose_name': 'תשלום במסמך',
                'verbose_name_plural': 'תשלומים במסמך',
                'db_table': 'document_payments',
            },
        ),
        migrations.CreateModel(
            name='DocumentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='מק"ט')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='תיאור')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='כמות')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='מחיר יחידה')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ שורה')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.formaldocument')),
            ],
            options={
                'verbose_name': 'שורת פריט',
                'verbose_name_plural': 'שורות פריטים',
                'db_table': 'document_line_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'document_counters',
                'unique_together': {('document_type', 'year')},
            },
        ),
    ]
