# Generated by Django 4.2.11 on 2026-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentcounter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documentcounter',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='documentcounter',
            name='document_type',
        ),
    ]
