# Generated by Django 4.2.11 on 2026-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentcounter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaldocument',
            name='draft_target_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='סוג מסמך לאחר אישור'),
        ),
        migrations.AlterField(
            model_name='formaldocument',
            name='document_type',
            field=models.CharField(choices=[('tax_invoice', 'חשבונית מס'), ('receipt', 'קבלה'), ('combined', 'חשבונית מס/קבלה'), ('transaction_invoice', 'חשבונית עסקה'), ('credit_invoice', 'חשבונית מס זיכוי'), ('draft', 'טיוטה')], max_length=30, verbose_name='סוג מסמך'),
        ),
    ]
