# Generated by Django 4.2.11 on 2026-09-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_businesses'),
        ('documents', '0004_draft_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaldocument',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.business', verbose_name='עסק'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.businesscategory', verbose_name='קטגוריה בעסק'),
        ),
    ]
