# Generated by Django 4.2.11 on 2026-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_business_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='סדרה')),
                ('year', models.PositiveIntegerField(verbose_name='שנת מס')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'document_series',
                'unique_together': {('series', 'year')},
            },
        ),
    ]
