# Generated by Django 4.2.11 on 2026-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaldocument',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='שם לקוח'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='linked_document_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך המסמך המקורי'),
        ),
    ]
