# Generated by Django 4.2.11 on 2026-09-14 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_credit_note_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaldocument',
            name='allocation_entered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='מועד הזנת ההקצאה'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='allocation_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_numbers_entered', to=settings.AUTH_USER_MODEL, verbose_name='מי הזין'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='allocation_number',
            field=models.CharField(blank=True, help_text='9 הספרות שהתקבלו מרשות המסים. מודפס על המסמך ומדווח ב-PCN874.', max_length=20, verbose_name='מספר הקצאה'),
        ),
    ]
