# Generated by Django 4.2.11 on 2026-09-14 13:09
#
# The customers dependency points at 0017 and not at a migration makemigrations
# wanted to create alongside this one: that would have carried a RenameIndex on
# cronheartbeat and an AlterField on payment.registration_fee, which are
# pre-existing model/migration drift and have nothing to do with cash plans.
# Carrying them here would apply somebody else's pending schema change without
# anyone deciding to.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_business_default_categories'),
        ('courses', '0021_lesson_trial_registration_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0017_computerized_docs_consent'),
        ('documents', '0007_credit_note_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='תיאור')),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='active', max_length=20, verbose_name='סטטוס')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='סכום ששולם במזומן')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='מחיר החוג הרגיל — הסכום שיופיע על המסמך של כל חודש.', max_digits=12, verbose_name='סכום חודשי')),
                ('monthly_document_type', models.CharField(choices=[('combined', 'חשבונית מס/קבלה'), ('tax_invoice', 'חשבונית מס')], default='combined', max_length=20, verbose_name='סוג המסמך החודשי')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='סניף')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_plans', to='customers.child', verbose_name='ילד')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_plans_created', to=settings.AUTH_USER_MODEL, verbose_name='נרשם על ידי')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_plans', to='courses.lesson', verbose_name='שיעור')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_plan_receipt', to='documents.formaldocument', verbose_name='קבלה')),
            ],
            options={
                'verbose_name': 'מנוי במזומן',
                'verbose_name_plural': 'מנויים במזומן',
                'db_table': 'cash_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashPlanMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='תאריך המסמך')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='סכום')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('invoiced', 'הופקה חשבונית')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('invoiced_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד ההפקה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_plan_month', to='documents.formaldocument', verbose_name='מסמך')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='documents.cashplan', verbose_name='תוכנית')),
            ],
            options={
                'verbose_name': 'חודש במנוי מזומן',
                'verbose_name_plural': 'חודשים במנוי מזומן',
                'db_table': 'cash_plan_months',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='cash_plan_m_status_2bcdc2_idx')],
                'unique_together': {('plan', 'due_date')},
            },
        ),
        migrations.AddIndex(
            model_name='cashplan',
            index=models.Index(fields=['child', 'status'], name='cash_plans_child_i_98215c_idx'),
        ),
    ]
