# Generated by Django 4.2.11 on 2026-09-14 13:31
#
# Two features branched off the same commit and each took 0008, which left the
# documents app with two leaf migrations and made `migrate` refuse to run at
# all — production build included. This carries no operations: it exists only
# to join the two branches back into one line.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_allocation_number'),
        ('documents', '0008_cash_plan'),
    ]

    operations = [
    ]
