# Generated by Django 4.2.11 on 2026-09-18 01:49
#
# A run may continue the previous software's run of its type: `start` is the
# run's first number (1 for every existing row, so nothing already issued
# changes), and DocumentSeriesOpening records who set a start above 1, when,
# and from which old number. Expand-only: one column with a default (kept in
# the database, below), one table.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0009_merge_0008_allocation_number_0008_cash_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentseries',
            name='start',
            field=models.PositiveIntegerField(default=1, verbose_name='מספר פתיחה'),
        ),
        # Django drops the column default once the rows are filled. Keep it in
        # the database: the build migrates before the new code is live, and
        # code that does not know `start` yet (or code rolled back to) creates a
        # run with the insert it always made, which must still get start = 1.
        migrations.RunSQL(
            sql='ALTER TABLE "document_series" ALTER COLUMN "start" SET DEFAULT 1;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='DocumentSeriesOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='סדרה')),
                ('year', models.PositiveIntegerField(verbose_name='שנת מס')),
                ('start', models.PositiveIntegerField(verbose_name='המספר הראשון בסדרה')),
                ('previous_last_number', models.PositiveIntegerField(verbose_name='המספר האחרון בתוכנה הקודמת')),
                ('previous_type_label', models.CharField(max_length=50, verbose_name='סוג המסמך בתוכנה הקודמת')),
                ('note', models.TextField(blank=True, verbose_name='מקור / סיבה')),
                ('created_by_name', models.CharField(blank=True, max_length=150, verbose_name='שם הפותח')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='מתי')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_openings', to=settings.AUTH_USER_MODEL, verbose_name='מי פתח')),
            ],
            options={
                'db_table': 'document_series_openings',
                'ordering': ['year', 'series'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentseriesopening',
            constraint=models.UniqueConstraint(fields=('series', 'year'), name='series_opening_once_per_run'),
        ),
        migrations.AddConstraint(
            model_name='documentseriesopening',
            constraint=models.UniqueConstraint(fields=('year', 'previous_type_label'), name='series_opening_one_run_per_old_run'),
        ),
        migrations.AddConstraint(
            model_name='documentseriesopening',
            constraint=models.CheckConstraint(check=models.Q(('start', django.db.models.expressions.CombinedExpression(models.F('previous_last_number'), '+', models.Value(1)))), name='series_opening_continues_the_old_run'),
        ),
    ]
