# Generated by Django 4.2.11 on 2026-09-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_signed_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedoriginal',
            name='channel',
            field=models.CharField(blank=True, choices=[('', 'לא נשלח על ידי המערכת'), ('ir', 'מייל קבלת חוג'), ('store', 'מייל חנות האתר'), ('credit_note', 'מייל הודעת זיכוי'), ('rental', 'מייל קבלת שכירות'), ('michal', 'מייל חשבונית מיכל קגן')], default='', max_length=20, verbose_name='ערוץ שליחה'),
        ),
    ]
