"""The columns and the table the documents fixes of 25.9.2026 build on — nothing uses them yet.

- formal_documents: issued_at / issued_by (a draft is issued when approved, not
  when typed), customer_ack_at / customer_ack_note (הוראה 23א(3): a credit note
  counts once the customer confirms it), withholding_amount (ניכוי במקור).
- document_payments: card_brand, paid_on (a transfer's value date).
- document_settlements: a receipt, a combined invoice-receipt or a credit note
  settling part of an invoice's balance — so an invoice can be seen paid.
- cash_plans: mode (NULL = a receipt now and a document each month), who cancelled.
- check_plans: who cancelled. check_items: bounced_at, replaced_by, credit_note.
- signed_originals.channel: 'formal', the mail channel for documents issued by hand.

Every column is nullable and the table is new: the code already deployed keeps
inserting rows while Vercel's build migrates the production database.
"""

# Generated by Django 4.2.11 on 2026-09-25 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0013_signedoriginal_channel_michal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashplan',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='בוטל'),
        ),
        migrations.AddField(
            model_name='cashplan',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='בוטל על ידי'),
        ),
        migrations.AddField(
            model_name='cashplan',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='אופן ההפקה'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='חזר'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.formaldocument', verbose_name='זיכוי'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='documents.checkitem', verbose_name="הוחלף בצ'ק"),
        ),
        migrations.AddField(
            model_name='checkplan',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='בוטל'),
        ),
        migrations.AddField(
            model_name='checkplan',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='בוטל על ידי'),
        ),
        migrations.AddField(
            model_name='documentpayment',
            name='card_brand',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='סוג כרטיס'),
        ),
        migrations.AddField(
            model_name='documentpayment',
            name='paid_on',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך התשלום'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='customer_ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='הלקוח אישר את קבלת הזיכוי'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='customer_ack_note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='איך אושרה הקבלה'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='מועד ההנפקה'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='הונפק על ידי'),
        ),
        migrations.AddField(
            model_name='formaldocument',
            name='withholding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ניכוי במקור'),
        ),
        migrations.AlterField(
            model_name='signedoriginal',
            name='channel',
            field=models.CharField(blank=True, choices=[('', 'לא נשלח על ידי המערכת'), ('ir', 'מייל קבלת חוג'), ('store', 'מייל חנות האתר'), ('credit_note', 'מייל הודעת זיכוי'), ('rental', 'מייל קבלת שכירות'), ('formal', 'מייל מסמך מהמשרד'), ('michal', 'מייל חשבונית מיכל קגן')], default='', max_length=20, verbose_name='ערוץ שליחה'),
        ),
        migrations.CreateModel(
            name='DocumentSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=40, verbose_name='מספר החשבונית')),
                ('invoice_kind', models.CharField(choices=[('formal', 'מסמך'), ('ir', 'קבלת חוג'), ('store', 'מכירת חנות'), ('legacy', 'מסמך מהתוכנה הקודמת')], default='formal', max_length=10, verbose_name='סוג החשבונית')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='סכום')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='בוטל')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='documents.formaldocument', verbose_name='החשבונית שנסגרת')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settles', to='documents.formaldocument', verbose_name='המסמך המשלם')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='בוטל על ידי')),
            ],
            options={
                'verbose_name': 'סגירת חשבונית',
                'verbose_name_plural': 'סגירות חשבוניות',
                'db_table': 'document_settlements',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['invoice_kind', 'invoice_number'], name='settlement_invoice_no_idx')],
            },
        ),
    ]
