"""A draft receipt's or invoice-receipt's chosen settlements, kept until it is approved (audit M11, 30.9.2026).

One nullable JSON column on formal_documents. Written only on a draft whose
target is a receipt or an invoice-receipt; read and cleared when the draft is
approved, when the settlements are recorded as DocumentSettlement rows and
checked against the balances of that moment. Nullable and additive: the code
already deployed keeps inserting rows while Vercel's build migrates production.
"""

# Generated by Django 4.2.11 on 2026-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_foundation_settlements_issue_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaldocument',
            name='draft_settlements',
            field=models.JSONField(blank=True, null=True, verbose_name='סגירות שייכתבו באישור הטיוטה'),
        ),
    ]
