"""A run may start above the previous software's last number plus one (1.10.2026).

The previous software still issues documents to the customers who have not
moved to kogo yet, so "last + 1" would be handed out by both programs. An
opening may now start further up; the numbers between are left to the previous
software. The CHECK goes from `start = previous_last_number + 1` to
`start > previous_last_number`.

Safe under the code already deployed: the new check is wider than the old one,
so every existing row, and every row the old code can still write while
Vercel's build migrates production, satisfies it. Going back is refused by the
database once an opening with a reserved range exists — that is a forward-fix.
"""

# Generated by Django 4.2.11 on 2026-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_draft_settlements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentseriesopening',
            name='series_opening_continues_the_old_run',
        ),
        migrations.AddConstraint(
            model_name='documentseriesopening',
            constraint=models.CheckConstraint(check=models.Q(('start__gt', models.F('previous_last_number'))), name='series_opening_continues_the_old_run'),
        ),
    ]
