# Generated by Django 4.2.11 on 2026-09-11 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    # Pinned to the last committed migrations. makemigrations also proposes a
    # customers migration for pre-existing model/migration drift (an index
    # rename and a field alteration unrelated to signatures); it is not part
    # of this change and was not kept, so nothing here may depend on it.
    dependencies = [
        ('customers', '0017_computerized_docs_consent'),
        ('core', '0020_terms_computerized_docs_clause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('registration_terms', 'תקנון הרשמה'), ('rental_contract', 'חוזה שכירות')], db_index=True, max_length=40, verbose_name='סוג')),
                ('signed_at', models.DateTimeField(db_index=True, verbose_name='מועד החתימה')),
                ('signer_name', models.CharField(max_length=200, verbose_name='שם החותם')),
                ('signer_id_number', models.CharField(blank=True, max_length=20, verbose_name='ת.ז. החותם')),
                ('signer_phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון החותם')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל החותם')),
                ('document_title', models.CharField(max_length=200, verbose_name='כותרת המסמך')),
                ('document_html', models.TextField(verbose_name='נוסח המסמך כפי שנחתם')),
                ('document_sha256', models.CharField(max_length=64, verbose_name='SHA-256 של המסמך')),
                ('consents', models.JSONField(blank=True, default=dict, verbose_name='הסכמות')),
                ('signature_png', models.BinaryField(verbose_name='תמונת החתימה (PNG)')),
                ('signature_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 של החתימה')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='דפדפן')),
                ('source', models.CharField(choices=[('widget', "ווידג'ט הרשמה")], default='widget', max_length=20, verbose_name='מקור')),
                ('refs', models.JSONField(blank=True, default=dict, verbose_name='הפניות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='core.branch', verbose_name='סניף')),
                ('business_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='customers.businesscustomer', verbose_name='לקוח עסקי')),
                ('children', models.ManyToManyField(blank=True, related_name='signatures', to='customers.child', verbose_name='ילדים')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='customers.family', verbose_name='משפחה')),
            ],
            options={
                'verbose_name': 'חתימה',
                'verbose_name_plural': 'חתימות',
                'db_table': 'signatures',
                'ordering': ['-signed_at', '-created_at'],
            },
        ),
    ]
