# Generated by Django 4.2.11 on 2026-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        # A new choice only: no SQL runs on the signatures table. The lock
        # timeout is here as on every tenant-path migration, so a future edit
        # that does touch the table fails the build after 5s rather than
        # queue the widget's signature inserts behind it.
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='signature',
            name='source',
            field=models.CharField(choices=[('widget', "ווידג'ט הרשמה"), ('signing_link', 'קישור לחתימה')], default='widget', max_length=20, verbose_name='מקור'),
        ),
    ]
