# Generated by Django 4.2.11 on 2026-10-10 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Every table of this app holds phones and the text of conversations. In
# production the database is also reachable through Supabase's public data API
# (docs/11-SECURITY-FINDING-ANON-EXPOSURE.md), where a table without row level
# security is readable with the public key. Turning it on with no policy closes
# that door for every role except the table's owner — which is the role Django
# connects as, so the application itself reads and writes as before.
RLS_TABLES = (
    'wahub_tags',
    'wahub_quick_replies',
    'wahub_contacts',
    'wahub_contact_tags',
    'wahub_messages',
    'wahub_contact_events',
)


def enable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table)} ENABLE ROW LEVEL SECURITY')


def disable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table)} DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='כותרת')),
                ('text', models.TextField(verbose_name='נוסח')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'תשובה מוכנה',
                'verbose_name_plural': 'תשובות מוכנות',
                'db_table': 'wahub_quick_replies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='שם')),
                ('color', models.CharField(default='#64748b', max_length=9, verbose_name='צבע')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'תגית',
                'verbose_name_plural': 'תגיות',
                'db_table': 'wahub_tags',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='טלפון')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='שם')),
                ('manychat_subscriber_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('source', models.CharField(choices=[('whatsapp', 'וואטסאפ'), ('ad', 'מודעה'), ('broadcast_reply', 'תשובה לתפוצה'), ('kogo_trial', 'נרשם לניסיון במערכת'), ('kogo_signup', 'נרשם במערכת'), ('import', 'ייבוא'), ('manual', 'הוסף ידנית')], default='whatsapp', max_length=20)),
                ('first_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_text', models.CharField(blank=True, max_length=300)),
                ('last_message_direction', models.CharField(blank=True, choices=[('in', 'נכנסת'), ('out', 'יוצאת')], max_length=3)),
                ('last_message_sender', models.CharField(blank=True, choices=[('customer', 'לקוח'), ('bot', 'בוט'), ('office', 'משרד'), ('system', 'מערכת')], max_length=10)),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('waiting_since', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.CharField(choices=[('bot', 'הבוט עונה'), ('human', 'נציג עונה')], default='bot', max_length=10)),
                ('needs_human', models.BooleanField(default=False)),
                ('needs_human_reason', models.CharField(blank=True, max_length=200)),
                ('needs_human_at', models.DateTimeField(blank=True, null=True)),
                ('known_topic', models.CharField(blank=True, choices=[('trial', 'שיעור ניסיון'), ('registration', 'רישום לחוג'), ('info', 'בקשת פרטים'), ('other', 'אחר')], max_length=20)),
                ('known_course_type', models.CharField(blank=True, max_length=100)),
                ('known_city', models.CharField(blank=True, max_length=100)),
                ('known_branch_id', models.UUIDField(blank=True, null=True)),
                ('known_branch_name', models.CharField(blank=True, max_length=200)),
                ('known_child_age', models.CharField(blank=True, max_length=40)),
                ('known_interest', models.CharField(blank=True, choices=[('hot', 'רוצה להירשם'), ('warm', 'מתעניין'), ('cold', 'לא מעוניין כרגע'), ('none', 'לא ידוע')], max_length=10)),
                ('known_callback_on', models.DateField(blank=True, null=True)),
                ('known_flags', models.JSONField(blank=True, default=list)),
                ('known_summary', models.TextField(blank=True)),
                ('needs_analysis', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_source', models.CharField(blank=True, choices=[('ai', 'AI'), ('rules', 'כללים')], max_length=10)),
                ('kogo_outcome', models.CharField(blank=True, choices=[('not_found', 'לא נמצא במערכת'), ('in_system', 'קיים במערכת בלי רישום'), ('pending', 'התחיל רישום ולא סיים'), ('signup_declined', 'ניסה להירשם והחיוב נכשל'), ('trial_upcoming', 'רשום לשיעור ניסיון'), ('trial_only', 'עשה ניסיון ולא נרשם'), ('registered_after', 'נרשם אחרי הפנייה'), ('customer_before', 'לקוח רשום')], max_length=20)),
                ('kogo_family_id', models.UUIDField(blank=True, null=True)),
                ('kogo_child_ids', models.JSONField(blank=True, default=list)),
                ('kogo_detail', models.CharField(blank=True, max_length=300)),
                ('kogo_checked_at', models.DateTimeField(blank=True, null=True)),
                ('followup_status', models.CharField(blank=True, choices=[('waiting_us', 'מחכה לנו'), ('no_answer', 'לא ענה'), ('answered', 'ענה'), ('later', 'בזמן אחר'), ('registered', 'נרשם'), ('not_relevant', 'לא רלוונטי')], max_length=20)),
                ('followup_due', models.DateField(blank=True, null=True)),
                ('followup_note', models.TextField(blank=True)),
                ('followup_at', models.DateTimeField(blank=True, null=True)),
                ('touched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, db_table='wahub_contact_tags', related_name='contacts', to='wahub.tag')),
            ],
            options={
                'verbose_name': 'איש קשר',
                'verbose_name_plural': 'אנשי קשר',
                'db_table': 'wahub_contacts',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'נכנסת'), ('out', 'יוצאת')], max_length=3)),
                ('sender', models.CharField(choices=[('customer', 'לקוח'), ('bot', 'בוט'), ('office', 'משרד'), ('system', 'מערכת')], max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'טקסט'), ('voice', 'הודעה קולית'), ('image', 'תמונה'), ('template', 'תבנית'), ('other', 'אחר')], default='text', max_length=10)),
                ('media_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'התקבלה'), ('sent', 'נשלחה'), ('failed', 'נכשלה'), ('simulated', 'הדמיה')], default='received', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('manychat', 'ManyChat'), ('kogo', 'Kogo'), ('bot_import', 'ייבוא מהבוט'), ('manual', 'ידני')], default='manychat', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wahub.contact')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הודעה',
                'verbose_name_plural': 'הודעות',
                'db_table': 'wahub_messages',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['contact', 'id'], name='wahub_message_contact'), models.Index(fields=['sent_at'], name='wahub_message_sent_at')],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'נוצר'), ('followup_changed', 'סימון מעקב'), ('tags_changed', 'תגיות'), ('kogo_outcome_changed', 'מצב במערכת'), ('analyzed', 'סיכום אוטומטי'), ('handled_by_changed', 'מי עונה'), ('needs_human_changed', 'מבקש נציג'), ('note', 'הערה')], max_length=30)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wahub.contact')),
            ],
            options={
                'verbose_name': 'אירוע ביומן',
                'verbose_name_plural': 'יומן',
                'db_table': 'wahub_contact_events',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['contact', '-id'], name='wahub_event_contact')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(models.OrderBy(models.F('last_message_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='wahub_contact_last_msg'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(models.OrderBy(models.F('last_inbound_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='wahub_contact_last_in'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('needs_analysis', True)), fields=['last_message_at'], name='wahub_contact_to_analyze'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['kogo_checked_at'], name='wahub_contact_checked'),
        ),
        migrations.RunPython(enable_row_level_security, disable_row_level_security),
    ]
