# Generated by Django 4.2.11 on 2026-10-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# The new tables hold the bot's knowledge, what it would have answered real
# customers (with their messages), and the office's notes. In production the
# database is also reachable through Supabase's public data API
# (docs/11-SECURITY-FINDING-ANON-EXPOSURE.md), so row level security goes on
# for them exactly as 0001 did for the first six tables: no policy, owner only.
RLS_TABLES = (
    'wahub_knowledge_items',
    'wahub_knowledge_history',
    'wahub_shadow_replies',
    'wahub_trial_questions',
    'wahub_knowledge_proposals',
    'wahub_service_notes',
)


def enable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table)} ENABLE ROW LEVEL SECURITY')


def disable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table)} DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'גרסה של רשומת ידע',
                'verbose_name_plural': 'היסטוריית ידע',
                'db_table': 'wahub_knowledge_history',
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('profile', 'פרופיל הבוט'), ('style_rule', 'כלל עיצוב'), ('behavior_rule', 'כלל התנהגות'), ('phrasing', 'נוסח'), ('topic', 'נושא'), ('fact', 'עובדה'), ('contact', 'איש קשר'), ('link', 'קישור'), ('alias', 'כינוי'), ('special_day', 'יום מיוחד'), ('office_hours', 'שעות משרד')], max_length=20)),
                ('key', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('scope_level', models.CharField(choices=[('business', 'כל העסק'), ('city', 'עיר'), ('branch', 'סניף'), ('course_type', 'תחום'), ('course', 'חוג')], default='business', max_length=20)),
                ('scope_id', models.CharField(blank=True, max_length=64)),
                ('scope_label', models.CharField(blank=True, max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('when_to_say', models.CharField(choices=[('proactive', 'מיוזמתו כשרלוונטי'), ('if_asked', 'רק אם שואלים'), ('internal', 'הנחיה פנימית, לא נאמר ללקוח')], default='proactive', max_length=20)),
                ('example_good', models.TextField(blank=True)),
                ('example_bad', models.TextField(blank=True)),
                ('source_note', models.CharField(blank=True, db_index=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'רשומת ידע',
                'verbose_name_plural': 'ידע הבוט',
                'db_table': 'wahub_knowledge_items',
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('applied', 'הוחל על הידע')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('human_override', 'נציג ענה מעל הבוט'), ('bad_verdict', 'סימון 👎 על תשובת צל'), ('service_note', 'הערת שירות'), ('reviewer', 'סריקה יזומה של השיחות')], max_length=20)),
                ('pattern', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('change', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'הצעת עדכון לבוט',
                'verbose_name_plural': 'הצעות עדכון לבוט',
                'db_table': 'wahub_knowledge_proposals',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'הערת שירות',
                'verbose_name_plural': 'הערות שירות',
                'db_table': 'wahub_service_notes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShadowReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covers_message_ids', models.JSONField(blank=True, default=list)),
                ('text', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('knowledge_used', models.JSONField(blank=True, default=list)),
                ('took_ms', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('request_human', models.BooleanField(default=False)),
                ('request_human_reason', models.CharField(blank=True, max_length=200)),
                ('verdict', models.CharField(blank=True, choices=[('good', 'טוב'), ('bad', 'לא טוב')], max_length=10)),
                ('verdict_note', models.TextField(blank=True)),
                ('verdict_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'תשובת צל',
                'verbose_name_plural': 'תשובות צל',
                'db_table': 'wahub_shadow_replies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TrialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('pretend_now', models.DateTimeField(blank=True, null=True)),
                ('last_outbound', models.TextField(blank=True)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'שאלת ניסיון',
                'verbose_name_plural': 'שאלות ניסיון',
                'db_table': 'wahub_trial_questions',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_shadow_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='needs_shadow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'וואטסאפ'), ('ad', 'מודעה'), ('broadcast_reply', 'תשובה לתפוצה'), ('kogo_trial', 'נרשם לניסיון במערכת'), ('kogo_signup', 'נרשם במערכת'), ('import', 'ייבוא'), ('manual', 'הוסף ידנית'), ('demo', 'דמו')], default='whatsapp', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('needs_shadow', True)), fields=['last_inbound_at'], name='wahub_contact_to_shadow'),
        ),
        migrations.AddField(
            model_name='trialquestion',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.contact'),
        ),
        migrations.AddField(
            model_name='trialquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shadowreply',
            name='after_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.message'),
        ),
        migrations.AddField(
            model_name='shadowreply',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_replies', to='wahub.contact'),
        ),
        migrations.AddField(
            model_name='shadowreply',
            name='verdict_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicenote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.contact'),
        ),
        migrations.AddField(
            model_name='servicenote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicenote',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.message'),
        ),
        migrations.AddField(
            model_name='servicenote',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.knowledgeproposal'),
        ),
        migrations.AddField(
            model_name='knowledgeproposal',
            name='applied_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='knowledgeproposal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='wahub.contact'),
        ),
        migrations.AddField(
            model_name='knowledgeproposal',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeproposal',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.message'),
        ),
        migrations.AddField(
            model_name='knowledgeproposal',
            name='shadow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wahub.shadowreply'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgehistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wahub.knowledgeitem'),
        ),
        migrations.AddIndex(
            model_name='shadowreply',
            index=models.Index(fields=['contact', '-id'], name='wahub_shadow_contact'),
        ),
        migrations.AddIndex(
            model_name='shadowreply',
            index=models.Index(fields=['created_at'], name='wahub_shadow_created'),
        ),
        migrations.AddIndex(
            model_name='knowledgeproposal',
            index=models.Index(fields=['status', '-id'], name='wahub_proposal_status'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['kind', 'is_active'], name='wahub_knowledge_kind'),
        ),
        migrations.AddIndex(
            model_name='knowledgehistory',
            index=models.Index(fields=['item', '-version'], name='wahub_knowledge_hist_item'),
        ),
        migrations.RunPython(enable_row_level_security, disable_row_level_security),
    ]
