# Generated by Django 4.2.11 on 2026-01-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0001_initial'),
        ('courses', '0001_initial'),
        ('customers', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(max_length=100, verbose_name='סוג תזכורת')),
                ('days_before_end', models.PositiveIntegerField(verbose_name='ימים לפני סיום')),
                ('phone_number', models.CharField(max_length=20, verbose_name='טלפון')),
                ('message_content', models.TextField(verbose_name='תוכן הודעה')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('sent', 'נשלח'), ('failed', 'נכשל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='נשלח בתאריך')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_reminders', to='customers.child', verbose_name='ילד')),
            ],
            options={
                'verbose_name': 'תזכורת מנוי',
                'verbose_name_plural': 'תזכורות מנויים',
                'db_table': 'subscription_reminders',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('renew', 'חידוש'), ('cancel', 'ביטול'), ('expire', 'פג תוקף')], max_length=20, verbose_name='סוג פעולה')),
                ('previous_status', models.CharField(blank=True, max_length=50, verbose_name='סטטוס קודם')),
                ('new_status', models.CharField(blank=True, max_length=50, verbose_name='סטטוס חדש')),
                ('previous_end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום קודם')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום חדש')),
                ('performed_by', models.CharField(blank=True, max_length=200, verbose_name='מבצע')),
                ('reason', models.TextField(blank=True, verbose_name='סיבה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to='customers.child', verbose_name='ילד')),
            ],
            options={
                'verbose_name': 'לוג מנוי',
                'verbose_name_plural': 'לוגים מנויים',
                'db_table': 'subscription_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='שם אירוע')),
                ('event_date', models.DateField(verbose_name='תאריך')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='שעת התחלה')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='שעת סיום')),
                ('event_type', models.CharField(choices=[('one_time', 'חד פעמי'), ('weekly', 'שבועי')], default='one_time', max_length=20, verbose_name='סוג')),
                ('is_daily_event', models.BooleanField(default=False, verbose_name='אירוע יומי')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='מיקום')),
                ('color', models.CharField(blank=True, default='#9333ea', max_length=7, verbose_name='צבע')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='קבצים מצורפים')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('assigned_instructors', models.ManyToManyField(blank=True, related_name='assigned_events', to='instructors.instructor', verbose_name='מדריכים משויכים')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='core.branch', verbose_name='סניף')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='core.city', verbose_name='עיר')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='core.room', verbose_name='סטודיו')),
            ],
            options={
                'verbose_name': 'אירוע',
                'verbose_name_plural': 'אירועים',
                'db_table': 'schedule_events',
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField(verbose_name='תאריך מופע')),
                ('reason', models.TextField(blank=True, verbose_name='סיבה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='בוטל על ידי')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='courses.lesson', verbose_name='שיעור')),
            ],
            options={
                'verbose_name': 'ביטול שיעור (תאריך ספציפי)',
                'verbose_name_plural': 'ביטולי שיעורים (תאריך ספציפי)',
                'db_table': 'lesson_cancellations',
                'ordering': ['-occurrence_date', '-created_at'],
                'unique_together': {('lesson', 'occurrence_date')},
            },
        ),
    ]
