# Generated by Django 4.2.11 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_scheduleevent_weekly_repeat_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='weekly_day_times',
            field=models.JSONField(blank=True, default=dict, verbose_name='שעות לפי יום'),
        ),
    ]
