# Generated by Django 4.2.11 on 2026-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_backfill_weekly_day_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='סיום תוקף הסכם השכירות'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='תחילת תוקף הסכם השכירות'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='renter_id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ת.ז / ח.פ השוכר'),
        ),
    ]
