# Generated by Django 4.2.11 on 2026-09-11 10:58
"""Which tenancy holds a studio-rental event. Expand only: a nullable column, NULL on every existing event."""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        ('scheduling', '0006_scheduleevent_contract_end_date_and_more'),
    ]

    operations = [
        # ALTER TABLE takes an ACCESS EXCLUSIVE lock on schedule_events: every
        # calendar read waits for it. The change itself is instant (a nullable
        # column), but behind a long open transaction it would queue and stall
        # the calendar; giving up after 5s fails the build instead, and the
        # running deployment stays live.
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='scheduleevent',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='rentals.tenancy', verbose_name='הסכם שכירות'),
        ),
    ]
