# Generated by Django 4.2.11 on 2026-09-10 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_lesson_trial_registration_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=60, verbose_name='שם משפחה')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='טלפון')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום')),
                ('source', models.CharField(choices=[('manual', 'ידני'), ('import', 'מקובץ')], default='manual', help_text='ידני = הוקלד במשרד. מקובץ = נקרא מרשימת העירייה.', max_length=12, verbose_name='מקור')),
                ('normalized_name', models.CharField(default='', editable=False, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_students_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_students', to='courses.lesson', verbose_name='שיעור')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_students_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'תלמיד חיצוני',
                'verbose_name_plural': 'תלמידים חיצוניים',
                'db_table': 'external_students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalStudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField(verbose_name='תאריך מופע')),
                ('status', models.CharField(choices=[('present', 'נוכח'), ('absent', 'נעדר'), ('not_marked', 'לא סומן')], default='not_marked', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_student_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='external_students.externalstudent', verbose_name='תלמיד חיצוני')),
            ],
            options={
                'verbose_name': 'נוכחות תלמיד חיצוני',
                'verbose_name_plural': 'נוכחות תלמידים חיצוניים',
                'db_table': 'external_student_attendance',
                'ordering': ['-occurrence_date'],
                'indexes': [models.Index(fields=['occurrence_date', 'status'], name='external_st_occurre_8258f5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='externalstudentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'occurrence_date'), name='uniq_external_mark_per_occurrence'),
        ),
        migrations.AddIndex(
            model_name='externalstudent',
            index=models.Index(fields=['lesson', 'is_active'], name='external_st_lesson__5c4f79_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalstudent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('lesson', 'normalized_name'), name='uniq_active_external_student_per_lesson'),
        ),
    ]
