# Generated by Django 4.2.11 on 2026-09-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_lesson_trial_registration_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_seed_delivery_category'),
        ('external_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRosterImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('xlsx', 'גיליון'), ('pdf', 'סרוק')], max_length=8, verbose_name='סוג קובץ')),
                ('original_filename', models.CharField(max_length=255, verbose_name='שם הקובץ')),
                ('byte_size', models.PositiveIntegerField(default=0, verbose_name='גודל')),
                ('sheet_grid', models.JSONField(blank=True, default=list, editable=False)),
                ('period_label', models.CharField(blank=True, max_length=120, verbose_name='תקופה')),
                ('status', models.CharField(choices=[('uploaded', 'הועלה'), ('parsing', 'בקריאה'), ('parsed', 'נקרא'), ('applied', 'הוחל'), ('failed', 'נכשל'), ('discarded', 'בוטל')], default='uploaded', max_length=12, verbose_name='סטטוס')),
                ('units_total', models.PositiveIntegerField(default=0, verbose_name='קבוצות בקובץ')),
                ('units_done', models.PositiveIntegerField(default=0, verbose_name='קבוצות שנקראו')),
                ('stated_report_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='סה"כ לפי הקובץ')),
                ('error', models.TextField(blank=True, verbose_name='שגיאה')),
                ('model_id', models.CharField(blank=True, editable=False, max_length=40)),
                ('input_tokens', models.PositiveIntegerField(default=0, editable=False)),
                ('output_tokens', models.PositiveIntegerField(default=0, editable=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='תאריך החלה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_roster_imports_applied', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_roster_imports', to='core.branch', verbose_name='סניף')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_roster_imports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ייבוא רשימת עירייה',
                'verbose_name_plural': 'ייבוא רשימות עירייה',
                'db_table': 'external_roster_imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRosterImportUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField(verbose_name='סדר')),
                ('municipality_code', models.CharField(blank=True, max_length=40, verbose_name='קוד קבוצה בעירייה')),
                ('group_name', models.CharField(blank=True, max_length=200, verbose_name='שם הקבוצה')),
                ('slots_raw', models.CharField(blank=True, max_length=200, verbose_name='ימים ושעות בקובץ')),
                ('slots', models.JSONField(blank=True, default=list)),
                ('source_ref', models.JSONField(blank=True, default=dict, editable=False)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('running', 'בקריאה'), ('parsed', 'נקרא'), ('mismatch', 'לא תואם את הסכום בקובץ'), ('failed', 'נכשל'), ('skipped', 'דולג')], default='pending', max_length=12, verbose_name='סטטוס')),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0, editable=False)),
                ('attempts', models.PositiveIntegerField(default=0, editable=False)),
                ('error', models.TextField(blank=True, verbose_name='שגיאה')),
                ('stated_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='סה"כ לפי הקובץ')),
                ('match_state', models.CharField(choices=[('confirmed', 'לפי שיוך קודם'), ('exact', 'התאמה מדויקת'), ('ambiguous', 'כמה אפשרויות'), ('none', 'לא נמצא שיעור')], default='none', max_length=12, verbose_name='מצב התאמה')),
                ('candidates', models.JSONField(blank=True, default=list, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_lessons', models.ManyToManyField(blank=True, related_name='external_roster_units', to='courses.lesson', verbose_name='שיעורים מותאמים')),
                ('roster_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='external_students.externalrosterimport', verbose_name='ייבוא')),
            ],
            options={
                'verbose_name': 'קבוצה בייבוא',
                'verbose_name_plural': 'קבוצות בייבוא',
                'db_table': 'external_roster_import_units',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRosterImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60, verbose_name='שם פרטי')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='שם משפחה')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='טלפון')),
                ('action', models.CharField(choices=[('add', 'הוספה'), ('keep', 'קיים'), ('remove', 'הסרה')], default='add', max_length=8, verbose_name='פעולה')),
                ('edited', models.BooleanField(default=False, verbose_name='נערך ידנית')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existing_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_import_rows', to='external_students.externalstudent', verbose_name='תלמיד קיים')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='external_students.externalrosterimportunit', verbose_name='קבוצה')),
            ],
            options={
                'verbose_name': 'שורה בייבוא',
                'verbose_name_plural': 'שורות בייבוא',
                'db_table': 'external_roster_import_rows',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRosterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('municipality_code', models.CharField(max_length=40, verbose_name='קוד קבוצה בעירייה')),
                ('group_name', models.CharField(blank=True, max_length=200, verbose_name='שם הקבוצה')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='תאריך אישור')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_roster_groups', to='core.branch', verbose_name='סניף')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_roster_groups_confirmed', to=settings.AUTH_USER_MODEL)),
                ('lessons', models.ManyToManyField(related_name='external_roster_groups', to='courses.lesson', verbose_name='שיעורים')),
            ],
            options={
                'verbose_name': 'שיוך קבוצת עירייה',
                'verbose_name_plural': 'שיוכי קבוצות עירייה',
                'db_table': 'external_roster_groups',
                'ordering': ['branch', 'municipality_code'],
            },
        ),
        migrations.AddIndex(
            model_name='externalrosterimportunit',
            index=models.Index(fields=['status', 'started_at'], name='external_ro_status_c5c847_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalrosterimportunit',
            constraint=models.UniqueConstraint(fields=('roster_import', 'ordinal'), name='uniq_roster_unit_ordinal'),
        ),
        migrations.AddIndex(
            model_name='externalrosterimportrow',
            index=models.Index(fields=['unit', 'action'], name='external_ro_unit_id_b840c8_idx'),
        ),
        migrations.AddIndex(
            model_name='externalrosterimport',
            index=models.Index(fields=['branch', 'status'], name='external_ro_branch__71633d_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalrostergroup',
            constraint=models.UniqueConstraint(fields=('branch', 'municipality_code'), name='uniq_roster_group_per_branch'),
        ),
    ]
