# Generated by Django 4.2.11 on 2026-09-08 05:51

import apps.payment_links.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_document_business_tags'),
        ('core', '0019_seed_delivery_category'),
        ('customers', '0015_recurring_override_store_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(default=apps.payment_links.models._new_slug, editable=False, max_length=24, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, verbose_name='תיאור לעמוד התשלום')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='תוקף עד')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='core.branch', verbose_name='סניף')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='core.business', verbose_name='עסק')),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='core.businesscategory', verbose_name='קטגוריה בעסק')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'קישור תשלום',
                'verbose_name_plural': 'קישורי תשלום',
                'db_table': 'payment_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120, verbose_name='שם האפשרות')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='payment_links.paymentlink')),
            ],
            options={
                'db_table': 'payment_link_options',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_label', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payer_name', models.CharField(max_length=120)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('completed', 'הושלם'), ('failed', 'נכשל'), ('review', 'לבדיקה')], default='pending', max_length=12)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100)),
                ('gateway_confirmation_code', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=30)),
                ('reported_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=10)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_link_payments', to='documents.formaldocument')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment_links.paymentlink')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment_links.paymentlinkoption')),
                ('tranzila_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_link_payments', to='customers.tranzilatransaction')),
            ],
            options={
                'db_table': 'payment_link_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['link', 'status'], name='payment_lin_link_id_343315_idx'), models.Index(fields=['ip_address', 'created_at'], name='payment_lin_ip_addr_1d5251_idx'), models.Index(fields=['payer_phone', 'created_at'], name='payment_lin_payer_p_3f9f4c_idx')],
            },
        ),
    ]
