# Generated by Django 4.2.11 on 2026-09-08 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_business_tags'),
        ('customers', '0015_recurring_override_store_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_seed_delivery_category'),
        ('payment_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('standing_order', 'הוראת קבע'), ('one_time', 'חיוב חד-פעמי')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('processing', 'בעיבוד'), ('completed', 'הושלם'), ('review', 'לבדיקה'), ('cancelled', 'בוטל')], default='pending', max_length=12)),
                ('include_registration_fee', models.BooleanField(default=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('charge_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_result', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_links', to='core.branch')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_links', to='core.business')),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_links', to='core.businesscategory')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_links', to='customers.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_links_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_links', to='courses.lesson')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_link', to='customers.payment')),
                ('recurring_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_links', to='customers.recurringpayment')),
            ],
            options={
                'db_table': 'card_links',
                'ordering': ['-created_at'],
            },
        ),
    ]
