# Generated by Django 4.2.11 on 2026-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    The hosted-page terminal each payment-link payment was taken on.

    A branch push runs `migrate` on the production database before its code
    reaches main (vercel_build.py), so for a while the running code does not
    know these columns. Django adds them NOT NULL and drops the default; an
    insert from that code would then fail. The database keeps the '' default,
    so those inserts land as "the michal pair", which is what they are.
    """

    dependencies = [
        ('payment_links', '0004_card_update_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlinkpayment',
            name='tranzila_terminal',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE payment_link_payments ALTER COLUMN tranzila_terminal SET DEFAULT ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
