# Generated by Django 4.2.11 on 2026-09-18 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_manychat_contact'),
        ('customers', '0021_child_status_add_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='שם הקובץ')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='טביעת הקובץ')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='מספר שורות')),
                ('status', models.CharField(choices=[('preview', 'תצוגה מקדימה'), ('committed', 'יובא')], default='preview', max_length=20, verbose_name='סטטוס')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='שורות')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='סיכום')),
                ('mapping', models.JSONField(blank=True, default=dict, verbose_name='מיפוי מיקומים')),
                ('include_subscription_parents', models.BooleanField(default=False, verbose_name='כולל הורים משלמי מנוי')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='תוצאת הייבוא')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='מועד ההעלאה')),
                ('committed_at', models.DateTimeField(blank=True, null=True, verbose_name='מועד הייבוא')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_imports_committed', to=settings.AUTH_USER_MODEL, verbose_name='יובא על ידי')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_imports', to=settings.AUTH_USER_MODEL, verbose_name='הועלה על ידי')),
            ],
            options={
                'verbose_name': 'ייבוא מהתוכנה הקודמת',
                'verbose_name_plural': 'ייבואים מהתוכנה הקודמת',
                'db_table': 'legacy_imports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_type', models.CharField(max_length=60, verbose_name='סוג המסמך בתוכנה הקודמת')),
                ('doc_type', models.CharField(choices=[('combined', 'חשבונית מס/קבלה'), ('tax_invoice', 'חשבונית מס'), ('receipt', 'קבלה'), ('transaction_invoice', 'חשבונית עסקה'), ('credit_invoice', 'חשבונית מס זיכוי')], max_length=30, verbose_name='סוג המסמך')),
                ('number', models.PositiveBigIntegerField(verbose_name='מספר המסמך בתוכנה הקודמת')),
                ('document_date', models.DateField(verbose_name='תאריך')),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ חשבונית')),
                ('receipt_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ קבלה')),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ זיכוי')),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סכום הניכוי')),
                ('total_before_withholding', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ לפני ניכוי')),
                ('original_status', models.CharField(blank=True, max_length=60, verbose_name='סטטוס בתוכנה הקודמת')),
                ('payment_type', models.CharField(blank=True, max_length=60, verbose_name='סוג תשלום')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='4 ספרות כרטיס')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='מיקום בתוכנה הקודמת')),
                ('details', models.TextField(blank=True, verbose_name='פרטים')),
                ('remark', models.TextField(blank=True, verbose_name='הערה')),
                ('customer_key', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='מפתח לקוח')),
                ('customer_name', models.CharField(blank=True, max_length=300, verbose_name='שם הלקוח')),
                ('customer_email', models.CharField(blank=True, max_length=254, verbose_name='אימייל')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='טלפון')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_documents', to='core.branch', verbose_name='סניף')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_documents', to='core.business', verbose_name='עסק')),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_documents', to='core.businesscategory', verbose_name='קטגוריה בעסק')),
                ('business_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_documents', to='customers.businesscustomer', verbose_name='לקוח עסקי')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='legacy_import.legacyimport', verbose_name='הייבוא האחרון שכתב אותו')),
            ],
            options={
                'verbose_name': 'מסמך מהתוכנה הקודמת',
                'verbose_name_plural': 'מסמכים מהתוכנה הקודמת',
                'db_table': 'legacy_documents',
                'ordering': ['-document_date', '-number'],
                'indexes': [models.Index(fields=['business_customer', '-document_date'], name='legacy_doc_customer_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='legacydocument',
            constraint=models.UniqueConstraint(fields=('doc_type', 'number'), name='legacy_document_type_number_unique'),
        ),
    ]
